### PR TITLE
Adding motion guidelines

### PR DESCRIPTION
**Pull request by hodlhodl**

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml) | :warning:Warning | | [Details](#user-content-docs%2Ftoc.yml)
[docs/design/add-in-design-language.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/add-in-design-language.md) | :white_check_mark:Succeeded | |
[docs/design/using-motion-office-addins.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/using-motion-office-addins.md) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-character.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-character.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-expected.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-expected.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-purpose.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-purpose.gif) | :white_check_mark:Succeeded | |

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml)
 - **[Warning]** Invalid file link:(~/design/using-motions-office-addins.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C23%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201803230124113749-127%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NG3aZZSCxqW4MoYbg42qhXLlPxXkMrlzMhVpHxPRLHY%3D&st=2018-03-23T01%3A20%3A18Z&se=2018-04-23T01%3A25%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml) | :warning:Warning | | [Details](#user-content-docs%2Ftoc.yml)
[docs/design/add-in-design-language.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/add-in-design-language.md) | :white_check_mark:Succeeded | |
[docs/design/using-motion-office-addins.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/using-motion-office-addins.md) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-character.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-character.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-expected.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-expected.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-purpose.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-purpose.gif) | :white_check_mark:Succeeded | |

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml)
 - **[Warning]** Invalid file link:(~/design/using-motions-office-addins.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C23%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201803231613210755-127%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=j7Dqy81Zk0YZnr5vwaCCXeDTqDxPjYHECtHHhWaOvr0%3D&st=2018-03-23T16%3A09%3A33Z&se=2018-04-23T16%3A14%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml) | :warning:Warning | | [Details](#user-content-docs%2Ftoc.yml)
[docs/design/add-in-design-language.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/add-in-design-language.md) | :white_check_mark:Succeeded | |
[docs/design/using-motion-office-addins.md](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/design/using-motion-office-addins.md) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-character.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-character.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-expected.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-expected.gif) | :white_check_mark:Succeeded | |
[docs/images/add-in-motion-purpose.gif](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/images/add-in-motion-purpose.gif) | :white_check_mark:Succeeded | |

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/hodlhodl/office-js-docs-pr/blob/motion-guidelines/docs/toc.yml)
 - **[Warning]** Invalid file link:(~/design/using-motions-office-addins.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C23%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201803231615452556-127%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x6Ob28Xdb0iXoU1dA%2F3plRbPEC%2BGN3yFkXYLpo9BLLA%3D&st=2018-03-23T16%3A11%3A52Z&se=2018-04-23T16%3A16%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@hodlhodl I assume you'll fix the TOC warning when you publish this topic?

**Pull request merged**
