### PR TITLE
Revert "Update custom-functions-requirements.md"

### PR DESCRIPTION
**Pull request by akrantz**
This reverts commit 1dd87dd82510d3c1e3fd2e34ccb0e545a3355727.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[385c78b](https://github.com/akrantz/office-js-docs-pr/pull/766/commits/385c78b9972220a196fa7a1a5803bc8cf3d89dc1)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[385c78b](https://github.com/akrantz/office-js-docs-pr/pull/766/commits/385c78b9972220a196fa7a1a5803bc8cf3d89dc1)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[385c78b](https://github.com/akrantz/office-js-docs-pr/pull/766/commits/385c78b9972220a196fa7a1a5803bc8cf3d89dc1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-requirements.md](https://github.com/akrantz/office-js-docs-pr/blob/revert-keyur-commit/docs/excel/custom-functions-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902200243090558-766%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m94iRzfHX8Aix24ZMNfnb4aFcUVt873rUCvhTPK%2BULk%3D&st=2019-02-20T02%3A39%3A27Z&se=2019-03-23T02%3A44%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@akrantz this PR looks good to me -- do you want me to approve it and merge it?

**Comment by akrantz** [comment]
Sure. I was just trying to help @keyur32 revert his accidental change.

**Comment by kbrandl** [comment]
Thanks for the feedback, @akrantz -- I'm going to go ahead and merge this one. @keyur32 the changes you applied will be reverted in **master** and can be subsequently reapplied there when PR #767 gets approved/merged.

**Pull request merged**
