### PR TITLE
[Do not merge] Custom functions tutorial

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-tutorial-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/excel-tutorial-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-online-register-add-in-1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-online-register-add-in-1.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-1b.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-1b.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-2.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-cfs-stock-ticker-3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-cfs-stock-ticker-3.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/includes/file-tutorial-excel-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/includes/file-tutorial-excel-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809271733032946-422%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=T9J9T1v2kD%2BrQ89KiMelyfAZyD0%2Fo5wMfWBuR2%2BBkYA%3D&st=2018-09-27T17%3A29%3A34Z&se=2018-10-28T17%3A34%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock this is the new PR for the custom functions tutorial. Marking it as "Do Not Merge" for now, since you're still awaiting word from legal regarding the article's use of the IEX API.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-tutorial-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/excel-tutorial-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-online-register-add-in-1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-online-register-add-in-1.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-1b.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-1b.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-2.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-cfs-stock-ticker-3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-cfs-stock-ticker-3.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/includes/file-tutorial-excel-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/includes/file-tutorial-excel-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C28%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809282052399264-422%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sfVdbqdnRpDWJFL%2BqssUEGycvXeuM9VMWhWq8NwvMEU%3D&st=2018-09-28T20%3A48%3A58Z&se=2018-10-29T20%3A53%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-tutorial-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/excel-tutorial-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-online-register-add-in-1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-online-register-add-in-1.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-1b.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-1b.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-2.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-cfs-stock-ticker-3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-cfs-stock-ticker-3.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/includes/file-tutorial-excel-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/includes/file-tutorial-excel-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C28%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809282057155701-422%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a%2FbmVCXljh9waP88Z0BSspehVvhg5HoenDLtEfGKH9E%3D&st=2018-09-28T20%3A53%3A40Z&se=2018-10-29T20%3A58%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-tutorial-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/excel-tutorial-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-online-register-add-in-1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-online-register-add-in-1.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-1b.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-1b.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-2.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-cfs-stock-ticker-3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-cfs-stock-ticker-3.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/includes/file-tutorial-excel-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/includes/file-tutorial-excel-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C28%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809282103343778-422%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wG3Js69CbKuMSwYtnxXBKfi5baJul1Hq14t0agEf234%3D&st=2018-09-28T20%3A59%3A52Z&se=2018-10-29T21%3A04%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-tutorial-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/excel/excel-tutorial-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-online-register-add-in-1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-online-register-add-in-1.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-1b.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-1b.png) | :white_check_mark:Succeeded | |
[docs/images/excel-cf-register-add-in-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/excel-cf-register-add-in-2.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-cfs-stock-ticker-3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-cfs-stock-ticker-3.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/includes/file-tutorial-excel-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/includes/file-tutorial-excel-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-custom-functions-tutorial/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809290104451542-422%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UkR9v4Dm%2BzrsKLlo%2FlJAP7ozzzyvoBwJVE28FXVkxas%3D&st=2018-09-29T01%3A01%3A08Z&se=2018-10-30T01%3A06%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
