### PR TITLE
[Admin] (docs metadata) Update metadata attribute values for docs.

### PR DESCRIPTION
**Pull request by kbrandl**
This PR updates metadata attribute values to improve our ability to generate reports about this doc set. It does the following: 
- sets metadata attribute **ms.technology** to `add-ins` for all files in this doc set (by using **globalMetadata** config setting in **docfx.json**)
- sets metadata attribute **ms.prod** to the appropriate value in all files (by using **fileMetadata** config setting in **docfx.json** where feasible, and otherwise by setting this metadata attribute value in individual .md files)

**ms.prod** values set at the folder-level for the following folders:

| folder | **ms.prod** value |
|:-------|:----------------------|
|concepts |  non-product-specific|
|design | non-product-specific|
|develop | non-product-specific|
|excel | excel|
|onenote | onenote|
|overview | non-product-specific|
|powerpoint | powerpoint|
|project | project|
|publish | non-product-specific|
|reference | non-product-specific|
|reference/manifest | non-product-specific|
|reference/objectmodel/**/ | outlook|
|resources | non-product-specific|
|testing | non-product-specific|
|word | word|

**ms.prod** values set at the file-level for files in the following folders:
- quickstarts
- tutorials
- reference/overview
- reference/requirement-sets

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[c5bc52f](https://github.com/OfficeDev/office-js-docs-pr/pull/734/commits/c5bc52f68af346d46fab971d4b6494254883f599)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[c5bc52f](https://github.com/OfficeDev/office-js-docs-pr/pull/734/commits/c5bc52f68af346d46fab971d4b6494254883f599)_: 

:clock10: **Full build**: average full build time is _38 sec(s)_ [calculated from last _3_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[c5bc52f](https://github.com/OfficeDev/office-js-docs-pr/pull/734/commits/c5bc52f68af346d46fab971d4b6494254883f599)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/index.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/index.yml) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/excel-quickstart-angular.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/excel-quickstart-jquery.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/excel-quickstart-react.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/excel-quickstart-vue.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/onenote-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/powerpoint-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/powerpoint-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/project-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/project-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/quickstarts/word-quickstart.md) | :white_check_mark:Succeeded | |
[docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/overview/excel-add-ins-reference-overview.md) | :white_check_mark:Succeeded | |
[docs/reference/overview/onenote-add-ins-javascript-reference.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/overview/onenote-add-ins-javascript-reference.md) | :white_check_mark:Succeeded | |
[docs/reference/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/overview/visio-javascript-reference-overview.md) | :white_check_mark:Succeeded | |
[docs/reference/overview/word-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/overview/word-add-ins-reference-overview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/add-in-commands-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/add-in-commands-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/dialog-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/dialog-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/identity-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/identity-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/office-add-in-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/office-add-in-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/onenote-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/onenote-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/powerpoint-and-project-note.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/powerpoint-and-project-note.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/word-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/reference/requirement-sets/word-api-requirement-sets.md) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/tutorials/excel-tutorial.md) | :white_check_mark:Succeeded | |
[docs/tutorials/powerpoint-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/tutorials/powerpoint-tutorial.md) | :white_check_mark:Succeeded | |
[docs/tutorials/word-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-metadata-attributes/docs/tutorials/word-tutorial.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902052254095709-734%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uHeMuMiXYNdUAOJZ2zv4YIEow2ct4T3Hh7wFpH%2BeV5Q%3D&st=2019-02-05T22%3A50%3A32Z&se=2019-03-08T22%3A55%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@lindalu-MSFT the APEX team recently whitelisted the following combinations of **ms.prod** and **ms.technology** attribute values for the Add-ins docs, so this PR updates the values of those attributes in OfficeDev/office-js-docs-pr. 

image

Can you please review this PR? Thanks!

**Comment by lindalu-MSFT** [comment]
Hi @kbrandl , I saw this after I created the PR to merge to live. After I review, I'll merge this and push live again! Sorry for going about this backwards today!

**Comment by lindalu-MSFT** [comment]
@kbrandl I didn't squash and merge, for some reason I don't see the big ole green button... shouldn't it appear in front of me when I use the GitHub UI? At any rate, I'll check more closely next time. This merge, you'll see them all over again in the merge to live PR.

**Pull request merged**
