### PR TITLE
Kim's edits to Best Practices updates

### PR DESCRIPTION
**Pull request by kbrandl**
This PR contains the following changes:

- Updated section title to better describe contents of the section

- Added introductory info to provide context about what the mappings are, what they do...if the reader doesn't understand this first, then the 'best practices' info won't make much sense to them.

- Reworded sentence that introduces list of best practices to be written in an active voice (i.e., to eliminate the clause at the beginning of the sentence and avoid using the passive phrase "there are several best practices...")

- Updated the list of best practices.

    - Removed list item for "Function names and ids should match in the functions JSON file." list item because this isn't true. The whole point of having an `id` property in addition to the `name` property is so that you can set `name` property to a different (localized) value if necessary, while leaving the value of `id` unchanged/constant.

    - Removed list item that describes JSON syntax for custom function mappings; replaced with info about specifying custom function mappings using dot notation (per the outcome of our chat with Michael yesterday).

    - Added a few items to the list of best practices.

    - Included code samples that illustrate the best practices.

Please note you'll also see changes in this PR that make "end user" consistent throughout the doc set...and also includes Ricky's recent change about CDN (which is already in master).

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-error-handling.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-error-handling.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809272040161650-423%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BtQ%2FOQydP0zhiKJbgPIOWjA0H2KQ8cd2o8FZCTbkUf8%3D&st=2018-09-27T20%3A36%3A29Z&se=2018-10-28T20%3A41%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-error-handling.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-error-handling.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-edits-to-bps/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809272041120678-423%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hEOeT6O4UX40AnrginLoyWFHIxPsvoN2ZIfeR4LwX30%3D&st=2018-09-27T20%3A37%3A46Z&se=2018-10-28T20%3A42%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock this PR revises the updates you made to the Best Practices article in your `michelle-bps` branch. Please see the details that I've included in this PR's description for a list of changes I made, and before you merge this PR into your branch, I'd suggest that you compare your initial draft side-by-side with my updated draft:

- Michelle's draft: https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-best-practices?branch=michelle-bps#mapping-names

- Kim's updated draft:   https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-best-practices?branch=kb-edits-to-bps#mapping-function-names-to-json-metadata 

Please let me know if you have any questions. Thanks!

**Comment by kbrandl** [comment]
@mscharlock glad that this is helpful, thanks for the feedback!  I'm going to go ahead and merge this PR into your branch and then after the merge completes, I'll approve your PR (#420) and you can merge that one into **master**.

**Comment by kbrandl** [comment]
(I'll leave my `kb-edits-to-bps` branch active for a while longer today, to make sure you have time to finish the side-by-side comparison on the staging site.)

**Pull request merged**
