### PR TITLE
Excel object model

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
Split up the Excel fundamental concepts article:
1. Move Run options to its own article "Delay ..."
2. Move blank or null values section to it's own article "Blank ..."
3. Move requirement sets section to the existing Excel requirements article
4. Rename fundamental concepts article "Excel object model".

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[0fab003](https://github.com/OfficeDev/office-js-docs-pr/commits/0fab003c03e1a3a0529bffcb7c003e89e6071a37)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-delay-in-cell-edit.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-delay-in-cell-edit.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-delay-in-cell-edit?branch=pr-en-us-2152) | [Details](#user-content-3ea0d8c7-6448dc54)
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=pr-en-us-2152) | [Details](#user-content-ed0f0d53-6448dc54)
[docs/excel/excel-add-ins-blank-null-values.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-blank-null-values.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-core-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-core-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts?branch=pr-en-us-2152) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |

<a id="3ea0d8c7-6448dc54"></a>
### [docs/excel/excel-add-ins-delay-in-cell-edit.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-delay-in-cell-edit.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=master)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="ed0f0d53-6448dc54"></a>
### [docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/requirement-sets/excel-api-requirement-sets.md)
 - **Line 53, Column 185**: **[Warning-file-not-found]** `````Invalid file link: '../develop/specify-office-hosts-and-api-requirements.md'.`````
 - **Line 72, Column 17**: **[Warning-file-not-found]** `````Invalid file link: '../reference/manifest/requirements.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009032223061700-2152%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FNkUId6fAtI6mofQaTTqjCocWA10lXqUv81vEpjSG9I%3D&st=2020-09-03T22%3A18%3A50Z&se=2020-10-04T22%3A23%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6c9086a](https://github.com/OfficeDev/office-js-docs-pr/commits/6c9086afe4c6db4b9ad25e2f4e22f6f49411f812)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-blank-null-values.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-blank-null-values.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-core-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-core-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-delay-in-cell-edit.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-delay-in-cell-edit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-delay-in-cell-edit?branch=pr-en-us-2152) |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=pr-en-us-2152) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C3%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009032229408917-2152%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qAEXeH92oy70Wt%2Fi9P6PUt2MJ6pmdd3ZqzELy%2FgpDjM%3D&st=2020-09-03T22%3A25%3A17Z&se=2020-10-04T22%3A30%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by alison-mk — APPROVED** [review]
Looks great! A couple suggestions.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[025cec3](https://github.com/OfficeDev/office-js-docs-pr/commits/025cec3370d2bf206d6070c6f9d68b346842395e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-blank-null-values.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-blank-null-values.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-comments.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-comments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-conditional-formatting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-conditional-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-conditional-formatting?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-core-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-core-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-data-validation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-delay-in-cell-edit.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-delay-in-cell-edit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-delay-in-cell-edit?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-error-handling.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-error-handling?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-overview?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-advanced?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-tables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-worksheet-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-worksheet-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheet-functions?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheets?branch=pr-en-us-2152) |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/performance?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-jquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-vue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue?branch=pr-en-us-2152) |
[docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/overview/excel-add-ins-reference-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview?branch=pr-en-us-2152) |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=pr-en-us-2152) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/tutorials/excel-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?branch=pr-en-us-2152) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009042147414360-2152%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x2IhJAT5BoI8wNdCErRCwT9IYEJFb1Ytim%2BKIa5LYtk%3D&st=2020-09-04T21%3A43%3A22Z&se=2020-10-05T21%3A48%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[5c83391](https://github.com/OfficeDev/office-js-docs-pr/commits/5c83391ee4851214b9ffbceab5ef3d53fd574859)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-blank-null-values.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-blank-null-values.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-comments.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-comments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-conditional-formatting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-conditional-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-conditional-formatting?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-core-concepts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-core-concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-data-validation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-delay-in-cell-edit.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-delay-in-cell-edit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-delay-in-cell-edit?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-error-handling.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-error-handling.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-error-handling?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-events.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-overview?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-advanced?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-tables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-tables?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-worksheet-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-worksheet-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheet-functions?branch=pr-en-us-2152) |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheets?branch=pr-en-us-2152) |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/excel/performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/performance?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-angular.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-jquery.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-react.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react?branch=pr-en-us-2152) |
[docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/quickstarts/excel-quickstart-vue.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue?branch=pr-en-us-2152) |
[docs/reference/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/overview/excel-add-ins-reference-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/overview/excel-add-ins-reference-overview?branch=pr-en-us-2152) |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets?branch=pr-en-us-2152) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values?branch=pr-en-us-2152) |
[docs/tutorials/excel-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/excel-object-model/docs/tutorials/excel-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial?branch=pr-en-us-2152) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C4%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009042149472575-2152%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KRk9022lVSB1j3DsDVlDOgc4fn7%2BNKBpK3c0Yb5PYLU%3D&st=2020-09-04T21%3A45%3A29Z&se=2020-10-05T21%3A50%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
