### PR TITLE
Update get-started excel angular.

### PR DESCRIPTION
**Pull request by cakriwut**
Update example with latest yo office generator

- Add screenshot yo office, using angular typescript options
- Update instruction

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/yo-office-excel-angular-js.png](https://github.com/cakriwut/office-js-docs-pr/blob/update-yo-angular-article/docs/images/yo-office-excel-angular-js.png) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-angular-ts.png](https://github.com/cakriwut/office-js-docs-pr/blob/update-yo-angular-article/docs/images/yo-office-excel-angular-ts.png) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-angular.md](https://github.com/cakriwut/office-js-docs-pr/blob/update-yo-angular-article/docs/includes/file-get-started-excel-angular.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809151006345871-372%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=f2HDZgdT4bE9oraofMCy%2F6fJxZq%2BBGWUW0UnrRRkxIo%3D&st=2018-09-15T10%3A03%3A00Z&se=2018-10-16T10%3A08%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by cakriwut** [comment]
Can I propose this for issue #330 ?

**Comment by kbrandl** [comment]
@cakriwut thank you for the contribution! We're already in the process of updating the Angular quick start but I'll review your PR to see if it can be incorporated into the changes we've already got underway. Thanks again!

**Comment by kbrandl** [comment]
@cakriwut thanks again for the contribution; unfortunately we're not going to be able to merge this PR. As I mentioned previously, we were already in the midst of revising the Excel/Angular quick start article whenever you submitted this PR. Since our revisions to the article were very extensive, the changes you've proposed in this PR have been superceded by PR #497. Therefore, I'm going to have to close this PR.

**Pull request closed without merging**
