### PR TITLE
Merge to live!

### PR DESCRIPTION
**Pull request by lindalu-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[e08458e](https://github.com/OfficeDev/office-js-docs-pr/commits/e08458e3fdce93e3f2ba72987fe63c51db8794d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-fresh.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-fresh.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-monoline.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-monoline.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons.md) | :white_check_mark:Succeeded | |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | |
[docs/develop/authorize-to-microsoft-graph-without-sso.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph-without-sso.md) | :white_check_mark:Succeeded | |
[docs/develop/common-coding-issues.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/common-coding-issues.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md) | :white_check_mark:Succeeded | |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/images/SelectHost.JPG](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/SelectHost.JPG) | :white_check_mark:Succeeded | |
[docs/images/monoline-colors.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-colors.png) | :white_check_mark:Succeeded | |
[docs/images/monoline-grayshades.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-grayshades.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon1.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon10.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon10.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon11.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon11.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon12.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon12.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon13.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon13.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon14.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon14.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon15.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon15.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon16.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon16.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon17.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon17.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon18.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon18.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon19.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon19.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon2.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon20.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon20.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon21.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon21.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon22.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon22.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon23.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon23.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon24.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon24.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon25.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon25.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon26.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon26.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon27.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon27.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon28.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon28.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon29.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon29.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon3.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon30.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon30.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon31.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon31.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon32.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon32.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon4.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon4.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon5.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon5.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon6.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon6.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon7.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon7.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon8.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon8.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon9.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon9.png) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C11%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912110002523011-1491%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BEu%2Bkv8HhhE1d2bW1D1xbRaVUQzSYPAV5gyA1hK28DU%3D&st=2019-12-10T23%3A59%3A21Z&se=2020-01-11T00%3A04%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[752e59f](https://github.com/OfficeDev/office-js-docs-pr/commits/752e59f741768b450b59c63a4c5522ee285117e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-fresh.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-fresh.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-monoline.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-monoline.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons.md) | :white_check_mark:Succeeded | |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | |
[docs/develop/authorize-to-microsoft-graph-without-sso.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph-without-sso.md) | :white_check_mark:Succeeded | |
[docs/develop/common-coding-issues.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/common-coding-issues.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md) | :white_check_mark:Succeeded | |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/images/SelectHost.JPG](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/SelectHost.JPG) | :white_check_mark:Succeeded | |
[docs/images/monoline-colors.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-colors.png) | :white_check_mark:Succeeded | |
[docs/images/monoline-grayshades.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-grayshades.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon1.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon10.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon10.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon11.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon11.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon12.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon12.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon13.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon13.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon14.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon14.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon15.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon15.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon16.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon16.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon17.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon17.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon18.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon18.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon19.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon19.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon2.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon20.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon20.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon21.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon21.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon22.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon22.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon23.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon23.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon24.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon24.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon25.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon25.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon26.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon26.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon27.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon27.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon28.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon28.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon29.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon29.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon3.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon30.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon30.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon31.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon31.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon32.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon32.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon4.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon4.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon5.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon5.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon6.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon6.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon7.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon7.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon8.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon8.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon9.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon9.png) | :white_check_mark:Succeeded | |
[docs/reference/javascript-api-for-office-error-codes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office-error-codes.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C11%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912111413402485-1491%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GUhiQp1gvy9u2%2BYDfr75Rl05HHmIH6Gjw7YJQfiHnSM%3D&st=2019-12-11T14%3A10%3A11Z&se=2020-01-11T14%3A15%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@lindalu-MSFT FYI - 'm merging another PR to **live** now (it includes one more change than this PR that you opened yesterday) -- so I'm going to close this PR of yours, without merging.

**Comment by kbrandl** [comment]
@lindalu-MSFT disregard my prior comment -- I'm going to merge this PR of yours instead of creating a new one.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[752e59f](https://github.com/OfficeDev/office-js-docs-pr/commits/752e59f741768b450b59c63a4c5522ee285117e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-fresh.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-fresh.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons-monoline.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons-monoline.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-icons.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/design/add-in-icons.md) | :white_check_mark:Succeeded | |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | |
[docs/develop/authorize-to-microsoft-graph-without-sso.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/authorize-to-microsoft-graph-without-sso.md) | :white_check_mark:Succeeded | |
[docs/develop/common-coding-issues.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/common-coding-issues.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/create-sso-office-add-ins-aspnet.md) | :white_check_mark:Succeeded | |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/images/SelectHost.JPG](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/SelectHost.JPG) | :white_check_mark:Succeeded | |
[docs/images/monoline-colors.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-colors.png) | :white_check_mark:Succeeded | |
[docs/images/monoline-grayshades.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monoline-grayshades.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon1.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon1.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon10.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon10.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon11.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon11.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon12.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon12.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon13.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon13.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon14.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon14.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon15.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon15.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon16.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon16.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon17.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon17.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon18.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon18.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon19.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon19.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon2.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon20.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon20.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon21.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon21.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon22.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon22.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon23.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon23.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon24.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon24.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon25.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon25.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon26.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon26.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon27.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon27.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon28.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon28.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon29.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon29.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon3.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon3.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon30.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon30.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon31.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon31.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon32.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon32.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon4.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon4.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon5.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon5.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon6.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon6.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon7.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon7.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon8.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon8.png) | :white_check_mark:Succeeded | |
[docs/images/monolineicon9.png](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/images/monolineicon9.png) | :white_check_mark:Succeeded | |
[docs/reference/javascript-api-for-office-error-codes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/javascript-api-for-office-error-codes.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.diagnostics.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.userProfile.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C11%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912111421453660-1491%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6AkQjZO%2F8LyMqN7Qnus1C%2F7JKDMXPoDZVVx0AUjtUDA%3D&st=2019-12-11T14%3A18%3A40Z&se=2020-01-11T14%3A23%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
