### PR TITLE
[Outlook] (preview) Add OWA support for features

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ce1863c](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/ce1863c44594fe1252feacad712377e568f08fcf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907151802336151-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i%2B19xYDqzpvFpHKblw8UmJDQs8z%2BYFd13uiNigQtGXI%3D&st=2019-07-15T17%3A58%3A42Z&se=2019-08-15T18%3A03%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
Approved, but I wanted to ask about the "(new)". Isn't it implied that the support is new due to the nature of it being introduced in a requirement set?

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Thanks for asking. The "(new)" represents the OWA version and contrasts with the "(classic)" or old version.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[14d31f9](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/14d31f983988941c2c8fb9c8e65e1a7fd6dab3fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907181946092581-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GNjfhvBKrmfMwbDbCDtbIYXjKG8JxdAgzsrXxxeYufc%3D&st=2019-07-18T19%3A42%3A21Z&se=2019-08-18T19%3A47%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[8d427a3](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/8d427a3bd51d614d6f92d8d71cc688570193763b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-592d5f99)

<a id="592d5f99"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\pawg-s, target branch: master, target branch commit: c1d046f6e2218e31ae66355c6c18038913fdb4b7, source commit: 8d427a3bd51d614d6f92d8d71cc688570193763b.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182042237977-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sTpaPw%2BHyUqggXPt%2FejuHEMwcTr6hwXsHvtinfaKEP4%3D&st=2019-07-18T20%3A37%3A36Z&se=2019-08-18T20%3A42%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[fd266ab](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/fd266ab1a4906c8526efd7cb59580ef8227b63a2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ecfe4ad6)

<a id="ecfe4ad6"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\cosh-s, target branch: master, target branch commit: c1d046f6e2218e31ae66355c6c18038913fdb4b7, source commit: fd266ab1a4906c8526efd7cb59580ef8227b63a2.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182045207811-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cHRIIBwIZzsFFl2%2B07HFBSUBynKcQI7kJpI4AP%2B42EQ%3D&st=2019-07-18T20%3A40%3A33Z&se=2019-08-18T20%3A45%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d6fbc06](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/d6fbc06876aa0eb606dbbc77a48098d277064d60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182047285547-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DyPk372uXAJ8KmImIwl89uWGKx53AqdBCmG4h40u%2BNU%3D&st=2019-07-18T20%3A43%3A30Z&se=2019-08-18T20%3A48%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[576fbee](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/576fbee76a34342721ab13291ff3e8dda98487d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182050473643-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=78Kdkr4ChVq%2FQEJXdS1t%2F%2Fww4BP4pBma6ozGtt2KDeg%3D&st=2019-07-18T20%3A46%3A43Z&se=2019-08-18T20%3A51%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[15fc83c](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/15fc83cc1cc01a2427b8114aac3d15d9bf2a0b58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182221160831-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7HWy2vk0RnIBn47Mq7YWCB2pDAB5Oy%2BxCG19sf%2Brz%2FA%3D&st=2019-07-18T22%3A17%3A14Z&se=2019-08-18T22%3A22%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[24aa53e](https://github.com/OfficeDev/office-js-docs-pr/pull/1172/commits/24aa53e3ce3238c277fa468227d145309169fec8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/outlook-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-owa-support/docs/reference/requirement-sets/outlook-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907182226171587-1172%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lBNEozLxUsR3tHSv%2FDaKehm27ZGsTJAtG5%2Fyx6PtVf8%3D&st=2019-07-18T22%3A22%3A12Z&se=2019-08-18T22%3A27%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
