### PR TITLE
Updated the create and debug office add-ins doc

### PR DESCRIPTION
**Pull request by John-Hart**
Added a comment about the for the multi-factor auth setting in the Outlook project
Added a comment about a prompt for the localhost self-signed certificate
Added a Note about the prompt that may occur for the loopback setting

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[421a202](https://github.com/John-Hart/office-js-docs-pr/pull/862/commits/421a202eef04e16c8497187431997ac8acfd3eeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/John-Hart/office-js-docs-pr/blob/UpdateCreateDebug/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904020021531776-862%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PL391zfoJn5LWNoeR9CkPIjERQMcXAqF30zNBnm0oJY%3D&st=2019-04-02T00%3A18%3A16Z&se=2019-05-03T00%3A23%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by John-Hart** [comment]
#sign-off

**Comment by John-Hart** [comment]
@davidchesnut any chance you can take a quick look at this?  Visual Studio 2019 is linking to this page to describe the new loopback setting

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ca90ea3](https://github.com/John-Hart/office-js-docs-pr/pull/862/commits/ca90ea308e12a6e30416797b36434e9b38523029)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/John-Hart/office-js-docs-pr/blob/UpdateCreateDebug/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904101617307253-862%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=B7HRLdgvtFujEI25tw6YMRT8UI0nRdDeZsn38PfCjw4%3D&st=2019-04-10T16%3A13%3A46Z&se=2019-05-11T16%3A18%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
