### PR TITLE
[Outlook] (product bug) Workaround for file attachment issue

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**
Document workaround discussed in https://github.com/OfficeDev/office-js/issues/322 until bug fixed in Outlook on Windows.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[0732824](https://github.com/OfficeDev/office-js-docs-pr/commits/073282439317aa24d5dbe274c511954b11e04fa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912022332497569-1464%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cyh8nwJinnsmYQIqGcOHNqpIz%2FqDVtCADAA97QlIjWQ%3D&st=2019-12-02T23%3A29%3A02Z&se=2020-01-02T23%3A34%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[75b2f38](https://github.com/OfficeDev/office-js-docs-pr/commits/75b2f38859a4d1c199ff34fa0627ba9dd14f7950)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[75b2f38](https://github.com/OfficeDev/office-js-docs-pr/commits/75b2f38859a4d1c199ff34fa0627ba9dd14f7950)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912092045417536-1464%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7723NhKqzSy6pv3NHBXgbbXxXLOunq3phTfv%2FjpQwEs%3D&st=2019-12-09T20%3A41%3A56Z&se=2020-01-09T20%3A46%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6cc697b](https://github.com/OfficeDev/office-js-docs-pr/commits/6cc697bad21e38589d5ee584d0c01f4c06b9aec3)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6cc697b](https://github.com/OfficeDev/office-js-docs-pr/commits/6cc697bad21e38589d5ee584d0c01f4c06b9aec3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.1/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.3/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.4/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |
[docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-file-attch-bug/docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201912092056150348-1464%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wUZ9vCCVF%2BXipQGrj1rk50zbvYEMZmZWxTctrDCmayU%3D&st=2019-12-09T20%3A52%3A33Z&se=2020-01-09T20%3A57%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ElizabethSamuel-MSFT** [comment]
Need to make these changes in DefinitelyTyped instead.

**Pull request closed without merging**
