### PR TITLE
Changed Office Store to AppSource.

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | |
[docs/concepts/add-in-development-lifecycle.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/add-in-development-lifecycle.md) | :white_check_mark:Succeeded | |
[docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/concepts/requirements-for-running-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/requirements-for-running-office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-design-guidelines.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/add-in-design-guidelines.md) | :white_check_mark:Succeeded | |
[docs/design/automatically-open-a-task-pane-with-a-document.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/automatically-open-a-task-pane-with-a-document.md) | :white_check_mark:Succeeded | |
[docs/design/ui-elements/voice-guidelines.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/ui-elements/voice-guidelines.md) | :white_check_mark:Succeeded | |
[docs/design/usability-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/usability-testing.md) | :white_check_mark:Succeeded | |
[docs/design/ux-design-patterns.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/ux-design-patterns.md) | :white_check_mark:Succeeded | |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/create-sso-office-add-ins-aspnet.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/create-sso-office-add-ins-nodejs.md) | :white_check_mark:Succeeded | |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | |
[docs/develop/loading-the-dom-and-runtime-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/loading-the-dom-and-runtime-environment.md) | :white_check_mark:Succeeded | |
[docs/develop/localization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/localization.md) | :white_check_mark:Succeeded | |
[docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md) | :white_check_mark:Succeeded | |
[docs/develop/understanding-the-javascript-api-for-office.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/understanding-the-javascript-api-for-office.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/excel-add-ins-get-started-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/onenote/onenote-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/onenote/onenote-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |
[docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/overview/office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md) | :white_check_mark:Succeeded | |
[docs/project/project-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/project/project-add-ins.md) | :white_check_mark:Succeeded | |
[docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/centralized-deployment.md) | :white_check_mark:Succeeded | |
[docs/publish/host-an-office-add-in-on-microsoft-azure.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/host-an-office-add-in-on-microsoft-azure.md) | :white_check_mark:Succeeded | |
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |
[docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md) | :white_check_mark:Succeeded | |
[docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/publish.md) | :white_check_mark:Succeeded | |
[docs/testing/debug-add-ins-in-office-online.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/debug-add-ins-in-office-online.md) | :white_check_mark:Succeeded | |
[docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md) | :white_check_mark:Succeeded | |
[docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/testing-and-troubleshooting.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/word/word-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/word/word-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C24%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201801240000456911-74%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w%2BoyMKjbT3kTBQ1H3sHkA6cpEuZp8LlFjIaNA6nwUY4%3D&st=2018-01-23T23%3A56%3A39Z&se=2018-02-24T00%3A01%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
@kbrandl - Okay, thanks! There are a few instances that should stay, I think, because in the product UI it's still called "Store". I'll update the PR with the rest of the fixes.

**Comment by kbrandl** [comment]
Thanks, @Laura Graham<mailto:lauragra@microsoft.com>!  I thought perhaps that was the case, so I’ll defer to your expert judgement regarding which instances should be changed. Thanks for having a look :)

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | |
[docs/concepts/add-in-development-lifecycle.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/add-in-development-lifecycle.md) | :white_check_mark:Succeeded | |
[docs/concepts/privacy-and-security.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/concepts/requirements-for-running-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/requirements-for-running-office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-design-guidelines.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/add-in-design-guidelines.md) | :white_check_mark:Succeeded | |
[docs/design/automatically-open-a-task-pane-with-a-document.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/automatically-open-a-task-pane-with-a-document.md) | :white_check_mark:Succeeded | |
[docs/design/ui-elements/voice-guidelines.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/ui-elements/voice-guidelines.md) | :white_check_mark:Succeeded | |
[docs/design/usability-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/usability-testing.md) | :white_check_mark:Succeeded | |
[docs/design/ux-design-patterns.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/design/ux-design-patterns.md) | :white_check_mark:Succeeded | |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-aspnet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/create-sso-office-add-ins-aspnet.md) | :white_check_mark:Succeeded | |
[docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/create-sso-office-add-ins-nodejs.md) | :white_check_mark:Succeeded | |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | |
[docs/develop/loading-the-dom-and-runtime-environment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/loading-the-dom-and-runtime-environment.md) | :white_check_mark:Succeeded | |
[docs/develop/localization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/localization.md) | :white_check_mark:Succeeded | |
[docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/referencing-the-javascript-api-for-office-library-from-its-cdn.md) | :white_check_mark:Succeeded | |
[docs/develop/understanding-the-javascript-api-for-office.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/develop/understanding-the-javascript-api-for-office.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/excel-add-ins-get-started-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/onenote/onenote-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/onenote/onenote-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |
[docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/overview/office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/project/create-a-project-add-in-that-uses-rest-with-an-on-premises-odata-service.md) | :white_check_mark:Succeeded | |
[docs/project/project-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/project/project-add-ins.md) | :white_check_mark:Succeeded | |
[docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/centralized-deployment.md) | :white_check_mark:Succeeded | |
[docs/publish/host-an-office-add-in-on-microsoft-azure.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/host-an-office-add-in-on-microsoft-azure.md) | :white_check_mark:Succeeded | |
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |
[docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog.md) | :white_check_mark:Succeeded | |
[docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/publish/publish.md) | :white_check_mark:Succeeded | |
[docs/testing/debug-add-ins-in-office-online.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/debug-add-ins-in-office-online.md) | :white_check_mark:Succeeded | |
[docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md) | :white_check_mark:Succeeded | |
[docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/testing/testing-and-troubleshooting.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/word/word-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-appsource/docs/word/word-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C24%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201801241956296391-74%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cfWg4Bly8kjQKtOqNKQWjZeRgUIJp5McoupfmDAyOQg%3D&st=2018-01-24T19%3A52%3A42Z&se=2018-02-24T19%3A57%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Lauragra** [comment]
Okay, @kbrandl , take another look. Thanks!

**Comment by kbrandl** [comment]
@Lauragra -- looks great, thanks!  Please feel free to merge this PR to **master** whenever you're ready for it to be published.  (Per the normal process, once these changes are merged to **master**, they'll be published live the next time **master** gets merged to **live**.)

**Pull request merged**
