### PR TITLE
Updated for Visual Studio 2017 UI

### PR DESCRIPTION
**Pull request by davidchesnut**

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/dc-2017-2/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810182344431551-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6qs%2FfGRpxY%2F3qEsaP3Ijy%2BzpUT8Ak%2BkDQ7nuU5jiRB4%3D&st=2018-10-18T23%3A41%3A03Z&se=2018-11-18T23%3A46%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/dc-2017-2/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810182346035503-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fRC9koYfIEhUfRJBg%2F0FEd639deu88OBf2AiiEFdWfM%3D&st=2018-10-18T23%3A42%3A29Z&se=2018-11-18T23%3A47%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
I should explain that I removed about a paragraph of text about an HTTPS requirement. I didn't see this was the case anymore in VS 2017. If you use HTTP it puts the URL into the manifest correctly.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/dc-2017-2/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810182353102136-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xZQb1bZlWN3a%2FGo4EVuRNsmaSmkcasDeymnz5tZSiKs%3D&st=2018-10-18T23%3A49%3A47Z&se=2018-11-18T23%3A54%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/package-your-add-in-using-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/dc-2017-2/docs/publish/package-your-add-in-using-visual-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C19%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810190000113882-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YPbdcgxgK4hVIpBwFz%2BJuYmvnsECrYcMtOjLusQHwCY%3D&st=2018-10-18T23%3A56%3A30Z&se=2018-11-19T00%3A01%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
@Rick-Kirkham the "important" note that strongly recommends HTTPS is still in the text. You can see it in the preview. Sorry if that was unclear. I just removed the step for how to manually add HTTP using Visual Studio as it no longer behaves that way.

**Pull request merged**
