### PR TITLE
[Outlook] (preview) Add OWA support

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[11f5a1a](https://github.com/OfficeDev/office-js-docs-pr/commits/11f5a1a1c7cf70b5390554171c9d4ca78ab132dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-preview/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202004061811087263-1722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kUXv%2FwhVm1JX0KHkxqsCDzyRW09oq0sjTqhViuyPiy8%3D&st=2020-04-06T18%3A07%3A19Z&se=2020-05-07T18%3A12%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ElizabethSamuel-MSFT** [comment]
Close for now.

**Comment by ElizabethSamuel-MSFT** [comment]
Note OWA support only on AppendOnSend for now.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[11f5a1a](https://github.com/OfficeDev/office-js-docs-pr/commits/11f5a1a1c7cf70b5390554171c9d4ca78ab132dd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7077878f)

<a id="7077878f"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\s2kb-s, target branch: master, target branch commit: 81e964970d4c3ea421256860e6b67db0ea4dff5a, source commit: 11f5a1a1c7cf70b5390554171c9d4ca78ab132dd.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202004081524513080-1722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0bdWUOJuxeJQgCkbZHxDpDWz5U9yrh7Gqn7LwWK7Oo8%3D&st=2020-04-08T15%3A20%3A05Z&se=2020-05-09T15%3A25%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[0d4a8b4](https://github.com/OfficeDev/office-js-docs-pr/commits/0d4a8b4b30c9b8b3bd63eaa1f4f18589a4352bfa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-preview/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202004081529235336-1722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0KksU4ZUvbD41Pl3TMqr22lutAaKZ7sx0StJbgsO9eA%3D&st=2020-04-08T15%3A25%3A41Z&se=2020-05-09T15%3A30%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d3cff02](https://github.com/OfficeDev/office-js-docs-pr/commits/d3cff02d55e59420d2019356406cdd29f4399987)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-preview/docs/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202004081531563193-1722%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jbWEW6csQTXRXMTOC4HyOAWJfOX9wQ0%2FGDFwDSQukjw%3D&st=2020-04-08T15%3A28%3A10Z&se=2020-05-09T15%3A33%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
