### PR TITLE
[Common API] (Compressed File) Removing support notes for Compressed File on iOS

### PR DESCRIPTION
**Pull request by AlexJerabek**
iOS does not support the Compressed File requirement set. There will be a corresponding PR in Definitely Typed soon.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[4cb4d5c](https://github.com/OfficeDev/office-js-docs-pr/pull/988/commits/4cb4d5c669114dd4787a14e787e63042ac255ddc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/office-add-in-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/reference/requirement-sets/office-add-in-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905072002259504-988%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a%2Bri8VSSvakQ3lPVDqsfKC9hDhdUKCPUmRL%2FKkmVx3I%3D&st=2019-05-07T19%3A58%3A39Z&se=2019-06-07T20%3A03%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
Just received word from the product team this only applied to Excel on iOS.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[bea5f8d](https://github.com/OfficeDev/office-js-docs-pr/pull/988/commits/bea5f8dcbfc17d6f80a11783997889213415968f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/office-add-in-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/reference/requirement-sets/office-add-in-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905072015278737-988%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Li%2BISIdSmtZdxg3zTssKc1MiZ8RbkhjJEiDvPqBZBoI%3D&st=2019-05-07T20%3A11%3A39Z&se=2019-06-07T20%3A16%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[7899d96](https://github.com/OfficeDev/office-js-docs-pr/pull/988/commits/7899d96c5fc7c1d331ce2783de8a630140f15eea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905072016068309-988%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MEeyfpsTGZXtXz7QnTZuhZkSjxUc801I2crsSn9dA4c%3D&st=2019-05-07T20%3A12%3A57Z&se=2019-06-07T20%3A17%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[48103cd](https://github.com/OfficeDev/office-js-docs-pr/pull/988/commits/48103cd86e5faf51ef1882c4fca99b90eb21c5a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bdb88276)

<a id="bdb88276"></a>
###
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\ei3m-s, target branch: master, target branch commit: 81a42914908861bf553cf0c6f484d8070526aeb7, source commit: 48103cd86e5faf51ef1882c4fca99b90eb21c5a8.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905091555071466-988%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=s2FNktLGvq%2FdqVTCnyaa83wSqNOZxEdIvz3Plnjnvvg%3D&st=2019-05-09T15%3A50%3A23Z&se=2019-06-09T15%3A55%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[903740d](https://github.com/OfficeDev/office-js-docs-pr/pull/988/commits/903740dd6bd54adbf18c5ccbd9eb24e3cf79aa68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ComFile/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905091556403402-988%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BGX8ZJ3qLC%2FQVP3F%2B0H205gWfBBkSF7UBP7WfQDd7kc%3D&st=2019-05-09T15%3A52%3A56Z&se=2019-06-09T15%3A57%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
