### PR TITLE
[excel] (Quick Start) Adding section on trusting self-signed certificates to the vue quick start

### PR DESCRIPTION
**Pull request by AlexJerabek**
Giving this article a link to the [Adding Self-Signed Certificates as Trusted Root Certificate](https://github.com/OfficeDev/generator-office/blob/master/src/docs/ssl.md) article. This should match the other Excel quick starts.
This is in response to #720.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0151228](https://github.com/OfficeDev/office-js-docs-pr/pull/722/commits/0151228fa076a37bfdd451796fcdf182e89cf8ac)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0151228](https://github.com/OfficeDev/office-js-docs-pr/pull/722/commits/0151228fa076a37bfdd451796fcdf182e89cf8ac)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0151228](https://github.com/OfficeDev/office-js-docs-pr/pull/722/commits/0151228fa076a37bfdd451796fcdf182e89cf8ac)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0151228](https://github.com/OfficeDev/office-js-docs-pr/pull/722/commits/0151228fa076a37bfdd451796fcdf182e89cf8ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/includes/file-get-started-excel-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-QS/docs/includes/file-get-started-excel-vue.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C30%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201901302256508310-722%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ycbWPlTNMZu5RwG6LV4ibpDXCi7JnZIBvZen05DKmts%3D&st=2019-01-30T22%3A53%3A06Z&se=2019-03-02T22%3A58%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
Thanks @kbrandl. Yeah, there aren't certificates generated in the usual place. That said I'm still getting a certification error. I'll look into this more.
unsecure

**Pull request closed without merging**
