### PR TITLE
Sideloading office online

### PR DESCRIPTION
**Pull request by Rick-Kirkham**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[58eadcc](https://github.com/OfficeDev/office-js-docs-pr/pull/937/commits/58eadcc9f24dbe9e1daab39a05bbf7b24c82bdb7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sideloading-office-online/docs/testing/sideload-office-add-ins-for-testing.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904292036172416-937%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jEvGQsG2ukgYqEzobS0v1eH2U6wQfxw8SEHpzT%2BPNZI%3D&st=2019-04-29T20%3A32%3A25Z&se=2019-05-30T20%3A37%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Kirkham** [comment]
> Would it make more sense to give the complete instructions first, then have a set with the "Do steps 3-6" line?

@AlexJerabek Do you mean swap the order of the Office Online and O365 sections, so the longer one is first?

**Comment by AlexJerabek** [comment]
> Do you mean swap the order of the Office Online and O365 sections, so the longer one is first?
@Rick-Kirkham Yes, or fully describe steps 3-6 in the O365 section and shorten the Office Online steps.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[2330657](https://github.com/OfficeDev/office-js-docs-pr/pull/937/commits/2330657596d7cb9e8aed75ccb211861be1c5637c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sideloading-office-online/docs/testing/sideload-office-add-ins-for-testing.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904292245298175-937%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TwlOgK1Mu9RY51pRjcumcs%2FWqhTsgjgZlaqhRaZdRoY%3D&st=2019-04-29T22%3A41%3A45Z&se=2019-05-30T22%3A46%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
