### PR TITLE
[Outlook] (delegate) No EWS support

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[04157ac](https://github.com/OfficeDev/office-js-docs-pr/commits/04157ac93bd7511f78fcfeee83997e534a4eadbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/outlook/delegate-access.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-no-ews/docs/outlook/delegate-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?branch=pr-en-us-1988) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006261811206614-1988%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N%2BMhFHRrYXuVph9P3kG%2FD9H2yy7EFNNYncb5VJE6wRo%3D&st=2020-06-26T18%3A07%3A41Z&se=2020-07-27T18%3A12%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[915a5a9](https://github.com/OfficeDev/office-js-docs-pr/commits/915a5a9968171ba32098cdee19ee63035cff16fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/outlook/delegate-access.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-no-ews/docs/outlook/delegate-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?branch=pr-en-us-1988) |
[docs/reference/manifest/permissions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-no-ews/docs/reference/manifest/permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/permissions?branch=pr-en-us-1988) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006262232163403-1988%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E9Xl3IFJvjQ43MzJo7Y8RhQsk0XmMzhIREYFjlWGW%2F0%3D&st=2020-06-26T22%3A28%3A40Z&se=2020-07-27T22%3A33%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ElizabethSamuel-MSFT** [comment]
Also helps address https://github.com/OfficeDev/office-js-docs-reference/issues/724, and notes that ReadWriteMailbox permission required for REST.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[dc9c6da](https://github.com/OfficeDev/office-js-docs-pr/commits/dc9c6da242c6d4eb557779fe6e627cbe19306027)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/outlook/delegate-access.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-no-ews/docs/outlook/delegate-access.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?branch=pr-en-us-1988) |
[docs/reference/manifest/permissions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-no-ews/docs/reference/manifest/permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/permissions?branch=pr-en-us-1988) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006291846035757-1988%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hauaR9395d3lrIJp2D2Sv46RiUihX%2FZy%2BsUKG0td6mI%3D&st=2020-06-29T18%3A42%3A23Z&se=2020-07-30T18%3A47%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
