### PR TITLE
Migrate outlook add in page

### PR DESCRIPTION
**Pull request by KarenYin01**
Migrate the Outlook Add-in page to new designed landing page. Refer to [Dev Task 231649](https://dev.azure.com/ceapex/Engineering/_workitems/edit/231649). 

Here is the guidance of new designed landing page.
https://aka.ms/docslanding

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f5c7a88](https://github.com/KarenYin01/office-js-docs-pr/commits/f5c7a88b459ac1cf3acf1fe0d734629b81c1732b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md) | :warning:Warning | | [Details](#user-content-d93b521a-59556d27)
[docs/toc.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/toc.yml) | :warning:Warning | | [Details](#user-content-a2f50e64-59556d27)
[docs/outlook/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.md) | :white_check_mark:Succeeded | |
[docs/outlook/index.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.yml) | :white_check_mark:Succeeded | |

<a id="d93b521a-59556d27"></a>
### [docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md)
 - **Line 0**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/outlook/index.md).`````

<a id="a2f50e64-59556d27"></a>
### [docs/toc.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/toc.yml)
 - **Line 0**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/outlook/index.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C4%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006040738561889-1919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PMDkbczsHPLK9tjfTiovqSnWrJrnIUFG8N9gVOjuWv0%3D&st=2020-06-04T07%3A35%3A13Z&se=2020-07-05T07%3A40%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[c7982e2](https://github.com/KarenYin01/office-js-docs-pr/commits/c7982e298a6a743609070a0191ea456e5f43de9a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md) | :warning:Warning | | [Details](#user-content-d93b521a-97cf04ca)
[docs/outlook/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.md) | :white_check_mark:Succeeded | |
[docs/outlook/index.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.yml) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/toc.yml) | :white_check_mark:Succeeded | |

<a id="d93b521a-97cf04ca"></a>
### [docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md)
 - **Line 0**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/outlook/index.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C4%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006040747134491-1919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vMJLa2RSPXGCjxMBGofChS%2FaM5piuGXosN%2BOg653w84%3D&st=2020-06-04T07%3A43%3A56Z&se=2020-07-05T07%3A48%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f1a0808](https://github.com/KarenYin01/office-js-docs-pr/commits/f1a08089556ebad9eb053ae659d98266686d7a47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md) | :warning:Warning | | [Details](#user-content-d93b521a-5943f631)
[docs/outlook/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.md) | :white_check_mark:Succeeded | |
[docs/outlook/index.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.yml) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/toc.yml) | :white_check_mark:Succeeded | |

<a id="d93b521a-5943f631"></a>
### [docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md)
 - **Line 0**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/outlook/index.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006080553221890-1919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0TGU1ncYrWqlSADL8DTTkYqp3Do%2BLdNhpG6utmLoe8g%3D&st=2020-06-08T05%3A50%3A00Z&se=2020-07-09T05%3A55%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ElizabethSamuel-MSFT** [comment]
Closing and reopening to generate preview site.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f1a0808](https://github.com/KarenYin01/office-js-docs-pr/commits/f1a08089556ebad9eb053ae659d98266686d7a47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/index?branch=pr-en-us-1919) | [Details](#user-content-d93b521a-d9a5ea62)
[docs/outlook/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/index?branch=pr-en-us-1919) |
[docs/outlook/index.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/outlook/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/outlook/index?branch=pr-en-us-1919) |
[docs/toc.yml](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/outlook/index?branch=pr-en-us-1919) |

<a id="d93b521a-d9a5ea62"></a>
### [docs/index.md](https://github.com/KarenYin01/office-js-docs-pr/blob/Migrate-Outlook-Add-in-page/docs/index.md)
 - **Line 0**: **[Warning-[InvalidFileLink](https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-links?branch=master)]** `````Invalid file link:(~/outlook/index.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202006081627383463-1919%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p5DxHkWXy%2F9JLh89Kgq1zgpWNfyu6J9Taf1xnrbQrps%3D&st=2020-06-08T16%3A24%3A20Z&se=2020-07-09T16%3A29%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
