### PR TITLE
[Excel] (Custom Functions) Fixing Dialog sample

### PR DESCRIPTION
**Pull request by mscharlock**

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bad776a](https://github.com/OfficeDev/office-js-docs-pr/pull/716/commits/bad776aea9d6e68f72382bd9b8ea77b494a5a0ba)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bad776a](https://github.com/OfficeDev/office-js-docs-pr/pull/716/commits/bad776aea9d6e68f72382bd9b8ea77b494a5a0ba)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bad776a](https://github.com/OfficeDev/office-js-docs-pr/pull/716/commits/bad776aea9d6e68f72382bd9b8ea77b494a5a0ba)_: 

:clock10: **Incremental building**: average incremental building time is _28 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bad776a](https://github.com/OfficeDev/office-js-docs-pr/pull/716/commits/bad776aea9d6e68f72382bd9b8ea77b494a5a0ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-runtimefix/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201901291847337464-716%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BNn2O%2F2vxw13QnDAnlp1fJXLT3XA%2B6eicRjAr2PkGgA%3D&st=2019-01-29T18%3A43%3A56Z&se=2019-03-01T18%3A48%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mscharlock** [comment]
Also, writing this to remind myself: we need to update the reference docs with the latest version of the d.ts (since it has the correct info now)

**Comment by kbrandl** [comment]
@mscharlock FYI, I've re-titled this PR to add a space between `[Excel]` and `(Custom Functions)` so this string won't get rendered as a hyperlink.

**Pull request merged**
