### PR TITLE
Ux patterns updates

### PR DESCRIPTION
**Pull request by hodlhodl**
updates to UX patterns as discussed.

### CODE REVIEW

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml) | :x:Error | | [Details](#user-content-docs%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml)
 - **[Error]** W:\bvk4-s\docs\toc.yml is not a valid TOC File: W:\bvk4-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 9, Idx: 3594) - (Line: 108, Col: 9, Idx: 3594): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 108, Col: 9, Idx: 3594)..
 - **[Error]** Unable to load file: toc.yml via processor: ExperimentalTocDocumentProcessor: W:\bvk4-s\docs\toc.yml is not a valid TOC File: W:\bvk4-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 9, Idx: 3594) - (Line: 108, Col: 9, Idx: 3594): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 108, Col: 9, Idx: 3594)..
 - **[Error]** W:\bvk4-s\docs\toc.yml is not a valid TOC File: W:\bvk4-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 9, Idx: 3594) - (Line: 108, Col: 9, Idx: 3594): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 108, Col: 9, Idx: 3594)..
 - **[Error]** Unable to load file: toc.yml via processor: TocDocumentProcessor: W:\bvk4-s\docs\toc.yml is not a valid TOC File: W:\bvk4-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 9, Idx: 3594) - (Line: 108, Col: 9, Idx: 3594): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 108, Col: 9, Idx: 3594)..

<a name=""></a>
### []()
 - **[Error]** W:\bvk4-s\docs\toc.yml is not a valid TOC File: W:\bvk4-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 9, Idx: 3594) - (Line: 108, Col: 9, Idx: 3594): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 108, Col: 9, Idx: 3594)..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201806262353521576-226%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wYxm%2BlgCoj3%2F8VuYRTkrWRJGS9XH623j92%2F4vMZY9ao%3D&st=2018-06-26T23%3A49%3A34Z&se=2018-07-27T23%3A54%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml) | :x:Error | | [Details](#user-content-docs%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml)
 - **[Error]** W:\qunu-s\docs\toc.yml is not a valid TOC File: W:\qunu-s\docs\toc.yml is not a valid TOC file, detail: (Line: 107, Col: 9, Idx: 3592) - (Line: 107, Col: 9, Idx: 3592): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 107, Col: 9, Idx: 3592)..
 - **[Error]** W:\qunu-s\docs\toc.yml is not a valid TOC File: W:\qunu-s\docs\toc.yml is not a valid TOC file, detail: (Line: 107, Col: 9, Idx: 3592) - (Line: 107, Col: 9, Idx: 3592): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 107, Col: 9, Idx: 3592)..
 - **[Error]** Unable to load file: toc.yml via processor: TocDocumentProcessor: W:\qunu-s\docs\toc.yml is not a valid TOC File: W:\qunu-s\docs\toc.yml is not a valid TOC file, detail: (Line: 107, Col: 9, Idx: 3592) - (Line: 107, Col: 9, Idx: 3592): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 107, Col: 9, Idx: 3592)..
 - **[Error]** Unable to load file: toc.yml via processor: ExperimentalTocDocumentProcessor: W:\qunu-s\docs\toc.yml is not a valid TOC File: W:\qunu-s\docs\toc.yml is not a valid TOC file, detail: (Line: 107, Col: 9, Idx: 3592) - (Line: 107, Col: 9, Idx: 3592): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 107, Col: 9, Idx: 3592)..

<a name=""></a>
### []()
 - **[Error]** W:\qunu-s\docs\toc.yml is not a valid TOC File: W:\qunu-s\docs\toc.yml is not a valid TOC file, detail: (Line: 107, Col: 9, Idx: 3592) - (Line: 107, Col: 9, Idx: 3592): Expected &#39;SequenceStart&#39;, got &#39;MappingStart&#39; (at Line: 107, Col: 9, Idx: 3592)..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201806262356532773-226%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FMxClgIvBL%2F%2FPt4ObE9%2BIR3H1WG2QsLm1xGhJy3%2Bea0%3D&st=2018-06-26T23%3A52%3A36Z&se=2018-07-27T23%3A57%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml) | :x:Error | | [Details](#user-content-docs%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/ux-patterns-updates/docs/toc.yml)
 - **[Error]** W:\b2uv-s\docs\toc.yml is not a valid TOC File: W:\b2uv-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 12, Idx: 3624) - (Line: 108, Col: 12, Idx: 3624): Mapping values are not allowed in this context..
 - **[Error]** W:\b2uv-s\docs\toc.yml is not a valid TOC File: W:\b2uv-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 12, Idx: 3624) - (Line: 108, Col: 12, Idx: 3624): Mapping values are not allowed in this context..
 - **[Error]** Unable to load file: toc.yml via processor: TocDocumentProcessor: W:\b2uv-s\docs\toc.yml is not a valid TOC File: W:\b2uv-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 12, Idx: 3624) - (Line: 108, Col: 12, Idx: 3624): Mapping values are not allowed in this context..
 - **[Error]** Unable to load file: toc.yml via processor: ExperimentalTocDocumentProcessor: W:\b2uv-s\docs\toc.yml is not a valid TOC File: W:\b2uv-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 12, Idx: 3624) - (Line: 108, Col: 12, Idx: 3624): Mapping values are not allowed in this context..

<a name=""></a>
### []()
 - **[Error]** W:\b2uv-s\docs\toc.yml is not a valid TOC File: W:\b2uv-s\docs\toc.yml is not a valid TOC file, detail: (Line: 108, Col: 12, Idx: 3624) - (Line: 108, Col: 12, Idx: 3624): Mapping values are not allowed in this context..

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201806270001080025-226%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oSqdIlH3E4m2eaUu0UUvIURuTZJEfxXsnTbPvrS8u5A%3D&st=2018-06-26T23%3A56%3A48Z&se=2018-07-28T00%3A01%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by hodlhodl** [comment]
Closing PR. Will submit incrementally.

**Pull request closed without merging**
