### PR TITLE
[Excel] (Custom Functions) Update requirements

### PR DESCRIPTION
**Pull request by akrantz**
This has the changes that were previously committed and reverted so it can be reviewed.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bee5a68](https://github.com/akrantz/office-js-docs-pr/pull/767/commits/bee5a683d18dd6907a3d0d1229ff489b0fa94e04)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bee5a68](https://github.com/akrantz/office-js-docs-pr/pull/767/commits/bee5a683d18dd6907a3d0d1229ff489b0fa94e04)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[bee5a68](https://github.com/akrantz/office-js-docs-pr/pull/767/commits/bee5a683d18dd6907a3d0d1229ff489b0fa94e04)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902200249260935-767%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CLADYkMFApf72xmacCFkm%2BKWIwnGck%2F5JaaEP%2F7R07M%3D&st=2019-02-20T02%3A45%3A34Z&se=2019-03-23T02%3A50%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by akrantz** [comment]
I don't think so. @Keyur Patel<mailto:kepatel@microsoft.com> Can you verify?
________________________________

**Comment by akrantz** [comment]
Yea it was fixed in January; we have other bugs now

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidchesnut** [comment]
@akrantz can you restore Keyur's changes? Based on conversation with Keyur those changes were valid. I think we should accept them. Thanks!

**Comment by keyur32** [comment]
I don't think this is no longer needed given we're getting ready for GA and this requirement won't hold there.

**Comment by keyur32** [comment]
CLosing

**Pull request closed without merging**
