### PR TITLE
Metadata update for getting started docs

### PR DESCRIPTION
**Pull request by nokafor**
The data science and developer program team would like to recommend add-in getting started docs to users. However, we hit a few issues with the metadata:

1) Most platforms besides add-ins tag their overview docs as "conceptual" docs. When combining docs across all the platforms, the user now has to understand and distinguish between "overview" and "conceptual" docs (which adds a layer of confusion)
To alleviate this, I've changed the "ms.topic: overview" tags to "ms.topic: conceptual".

2) We are having trouble pulling the custom tags from telemetry. So, instead of calling the column "scenarios", I've added the ms.custom tag and nested scenarios there.

3) When combining the tutorials/quickstarts across products, we noticed the add-in tutorials and quickstarts were not being recommended. This was because they didn't have a language tag to map to user preferences. To fix this, I added languages to the ms.custom tag (only for tutorials and quickstarts)

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[1f28b56](https://github.com/OfficeDev/office-js-docs-pr/commits/1f28b56eb7ce8254b6faa4e4ee325451af39194a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/onenote/onenote-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/onenote/onenote-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |
[docs/overview/explore-with-script-lab.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/overview/explore-with-script-lab.md) | :white_check_mark:Succeeded | |
[docs/overview/office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/overview/office-add-ins.md) | :white_check_mark:Succeeded | |
[docs/powerpoint/powerpoint-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/powerpoint/powerpoint-add-ins.md) | :white_check_mark:Succeeded | |
[docs/project/project-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/project/project-add-ins.md) | :white_check_mark:Succeeded | |
[docs/reference/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/reference/overview/visio-javascript-reference-overview.md) | :white_check_mark:Succeeded | |
[docs/word/word-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/sokafor-metadata-pat/docs/word/word-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201910092246226394-1350%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jCVzrAMyZlwFT3v%2FnYQNG8%2BUkZNpVZVjS4XQ%2FkMIt5c%3D&st=2019-10-09T22%3A42%3A39Z&se=2019-11-09T22%3A47%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@nokafor looks good to me; I'll approve and merge this PR now.

Also, please note that the Outlook Add-ins docs live in a separate repo (**OfficeDev/outlook-dev-docs**) so the same type of metadata updates are needed there as well. I'll handle that myself now.

**Comment by kbrandl** [comment]
FYI, corresponding PR that I've submitted for the Outlook Add-ins doc updates is here: https://github.com/OfficeDev/outlook-dev-docs/pull/733.

**Comment by nokafor** [comment]
Thank you so much @kbrandl for helping with this!

**Pull request merged**
