### PR TITLE
Corrected Variable Scope

### PR DESCRIPTION
**Pull request by mlafleur**
- Rescoped the body variable from `var `to `let `( fixes issue #58 )
- Corrected minor markdown issues

### CODE REVIEW

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 128**: **[Error]** Pull content in folder W:\d04o-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:76cf022be0cf788dbfb30880f45e800d405b540a@github.com/Microsoft/templates.docs.msft/&#39; not found 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802071829450938-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fLY%2FC54qIE2j34EgRq7tQujwZrAUwIF0Mun1NGRgSZU%3D&st=2018-02-07T18%3A25%3A36Z&se=2018-03-10T18%3A30%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 128**: **[Error]** Pull content in folder W:\xqdl-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:76cf022be0cf788dbfb30880f45e800d405b540a@github.com/Microsoft/templates.docs.msft/&#39; not found 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802071832580076-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Wx75AxdeMDFaWJp8Iru9k3h%2FQIxq86fxGoylMLswqFY%3D&st=2018-02-07T18%3A28%3A46Z&se=2018-03-10T18%3A33%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 128**: **[Error]** Pull content in folder W:\fns4-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:76cf022be0cf788dbfb30880f45e800d405b540a@github.com/Microsoft/templates.docs.msft/&#39; not found 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802072140460038-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nCHVIF5B8dfQRUESJSxpc1LO1DD%2Bj%2BRGhFD8qPNoZPE%3D&st=2018-02-07T21%3A36%3A32Z&se=2018-03-10T21%3A41%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mlafleur** [comment]
Any idea what is triggering validation to fail? I've gone over the page several times but I'm not seeing any noticeable differences between it and those I've submitted in previous PRs.

**Comment by kbrandl** [comment]
@mlafleur -- I'll look into this build failure and let you know what I find out.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 128**: **[Error]** Pull content in folder W:\gnzo-s\_themes failed. Error: remote: Repository not found. fatal: repository &#39;https://username:76cf022be0cf788dbfb30880f45e800d405b540a@github.com/Microsoft/templates.docs.msft/&#39; not found 

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C8%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802081745101709-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wak2bPhxsCDlxxBA%2BqZdGXcNBLxTEWF%2BQbtHk%2BsewtQ%3D&st=2018-02-08T17%3A41%3A33Z&se=2018-03-11T17%3A46%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mlafleur -- this looks like an issue with the underlying build/validation system for the docs platform. I've opened a ticket with that team and will provide you with an update here when the issue is resolved.

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/using-office-ui-fabric-react.md](https://github.com/mlafleur/office-js-docs-pr/blob/fix-58/docs/design/using-office-ui-fabric-react.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802091833542461-86%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Hex38oWrAsnIm%2BInHN7HVBRHnwLJiq1asBQtKPMAdk4%3D&st=2018-02-09T18%3A29%3A46Z&se=2018-03-12T18%3A34%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mlafleur -- this was indeed an issue with the underlying build/validation system for the docs platform.  This issue has been addressed so builds are now completing successfully. I'll review your pending PRs today; thanks for the contributions!

**Pull request merged**
