### PR TITLE
[excel] (Preview APIs) Linking preview content to reference documentation

### PR DESCRIPTION
**Pull request by AlexJerabek**
This PR changes the links for Excel preview content from the open spec to the reference documentation. It also clarifies the note about using the preview APIs and makes it consistent across pages.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1f4bacd](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/1f4bacd2cb236ef6d4a26790acc03816f19a1c42)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1f4bacd](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/1f4bacd2cb236ef6d4a26790acc03816f19a1c42)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1f4bacd](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/1f4bacd2cb236ef6d4a26790acc03816f19a1c42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/performance.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902202147328376-772%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WkSGjf421NtmcFYc286XHqtt%2BR4VuN%2BaccNeaiwxxH8%3D&st=2019-02-20T21%3A43%3A43Z&se=2019-03-23T21%3A48%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[a28474b](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/a28474b9e60ac686d8cbc28a7942c16534101959)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[a28474b](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/a28474b9e60ac686d8cbc28a7942c16534101959)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[a28474b](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/a28474b9e60ac686d8cbc28a7942c16534101959)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/performance.md) | :white_check_mark:Succeeded | |
[docs/includes/using-preview-apis.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/includes/using-preview-apis.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902202348070401-772%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TixeGmiPpE8MGVHiSndG3nDawwIdgmZ67gxFJM%2F%2FCWQ%3D&st=2019-02-20T23%3A44%3A20Z&se=2019-03-23T23%3A49%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e5d97e3](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/e5d97e3a0c234284811eb77ebd8237820718524c)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by AlexJerabek** [comment]
Thanks @kbrandl. I've updated with the include file. [Looks like it works in a note](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-worksheets?branch=AlexJ-PreviewLinks#find-all-cells-with-matching-text-preview).

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e5d97e3](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/e5d97e3a0c234284811eb77ebd8237820718524c)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e5d97e3](https://github.com/OfficeDev/office-js-docs-pr/pull/772/commits/e5d97e3a0c234284811eb77ebd8237820718524c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/excel/performance.md) | :white_check_mark:Succeeded | |
[docs/includes/using-preview-apis.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-PreviewLinks/docs/includes/using-preview-apis.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902202354072442-772%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KFxFGtBek3Kdnz4n0ljF284DA0wYw%2BpMS9NMryC3au0%3D&st=2019-02-20T23%3A50%3A21Z&se=2019-03-23T23%3A55%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
