### PR TITLE
doc: add vue guide for excel add-in

### PR DESCRIPTION
**Pull request by trionfo1993**
Guide to create excel add-in by vue.js

### CODE REVIEW

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/includes/file-get-started-excel-vue.md](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/includes/file-get-started-excel-vue.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201801270908531618-82%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=za0jF97iEQhYUZ%2Fgw%2Fddc1oaI3rP1pzDuzNaJNgWrOA%3D&st=2018-01-27T09%3A04%3A40Z&se=2018-02-27T09%3A09%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@trionfo1993 -- thanks for the contribution!  We'll review this PR this week sometime and will let you know if we have any feedback prior to merging.

**Comment by kbrandl** [comment]
@trionfo1993 -- just touching base with a quick update.  I've reviewed this PR and it looks good overall.  I'm going to make a few (minor) changes (by pushing commits to your fork, which will automatically update this PR) before merging these changes into **master**, so the merge will likely happen next week. Thanks again for the contribution!

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/includes/file-get-started-excel-vue.md](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/includes/file-get-started-excel-vue.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C14%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802140051229200-82%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=seAr6ZCOgrRcVNeyHn0Vq4ZARInbl6IKOdW3UsXnt4U%3D&st=2018-02-14T00%3A47%3A12Z&se=2018-03-17T00%3A52%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-get-started-vue.md](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-get-started-vue.md) | :white_check_mark:Succeeded | |
[docs/images/vue-cli-prompts.png](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/images/vue-cli-prompts.png) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-vue.md](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/includes/file-get-started-excel-vue.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-vue.md](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/quickstarts/excel-quickstart-vue.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/trionfo1993/office-js-docs-pr/blob/master/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C14%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201802140058364213-82%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ls5mU%2Fv8t%2B30Exad20M1pz%2F4H0fUiz5G4cobMdEg0gY%3D&st=2018-02-14T00%3A54%3A29Z&se=2018-03-17T00%3A59%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
