### PR TITLE
[Excel] (Custom functions) Addresses how to return a matrix, repeatable parameters

### PR DESCRIPTION
**Pull request by mscharlock**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[c02f0ca](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/c02f0ca912773373d58e1a7360f7af15d615c6e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C28%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201906282126511341-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eaDX68%2BoCSkkqzyeQlFOpoR14k42gJOlEfIQ7DBcqL0%3D&st=2019-06-28T21%3A22%3A54Z&se=2019-07-29T21%3A27%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[10b925d](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/10b925d6a41dbd3536c5ce9a712caf0a286bf684)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa3b6bcd)

<a id="aa3b6bcd"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\3kt2-s, target branch: master, target branch commit: 93ae6208f396574e89352591be8c94aed2b8d638, source commit: 10b925d6a41dbd3536c5ce9a712caf0a286bf684.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907091756537046-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NlLis5DWlJEFMAelDnqA5hAfG4bBHsWrT7R%2BnBJPNPg%3D&st=2019-07-09T17%3A52%3A07Z&se=2019-08-09T17%3A57%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[03098c5](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/03098c59da5b3efcd1c2b342ea00ad782a205c1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907091939170793-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sVwY780zGmTM5v43lOLjjFThU14upLUUvIlMYhUHCL4%3D&st=2019-07-09T19%3A35%3A26Z&se=2019-08-09T19%3A40%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[463b1c6](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/463b1c692742165dfed917ed25921156bd0ba84f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907092307163209-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sKBl94oeMboQ1Nl6UJHTKHc4EooqskbfLVOiDRev%2FWU%3D&st=2019-07-09T23%3A03%3A14Z&se=2019-08-09T23%3A08%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[628df2d](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/628df2d04cf6d3cc883548980123c290670b67df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json-autogeneration.md) | :warning:Warning | | [Details](#user-content-32630023-2cc70eb2)
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

<a id="32630023-2cc70eb2"></a>
### [docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json-autogeneration.md)
 - **Line 218**: **[Warning]** `````Illegal link: `<a href="excel/custom-functions-parameter-options.md#addressing-cells-context-parameter">Addressing cell's context parameter</a>` -- missing bookmark. The file excel/custom-functions-parameter-options.md doesn't contain a bookmark named addressing-cells-context-parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907151915586825-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s6axER3OjF9lTm4ajmXRF3pwiRIwnLIzAUJJq5himuU%3D&st=2019-07-15T19%3A11%3A55Z&se=2019-08-15T19%3A16%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[5cd0dba](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/5cd0dbaeb126ab0e67ed27cd8017e739a6eaa999)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :warning:Warning | | [Details](#user-content-31e38006-c0c9a25e)
[docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json-autogeneration.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-volatile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-volatile.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

<a id="31e38006-c0c9a25e"></a>
### [docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md)
 - **Line 293**: **[Warning]** `````Invalid file link:(~/excel/custom-functions-best-practices.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907152136047832-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JZoxOGmID6F4baa4ukTETxKNLrLphbrOt2ZPCIaTqW0%3D&st=2019-07-15T21%3A32%3A01Z&se=2019-08-15T21%3A37%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[e2d6f56](https://github.com/OfficeDev/office-js-docs-pr/pull/1140/commits/e2d6f56ec9a1e2776e92a14d503e59a4f3a95fde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-json-autogeneration.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json-autogeneration.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-json.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-json.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-parameter-options.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-parameter-options.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-volatile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/excel/custom-functions-volatile.md) | :white_check_mark:Succeeded | |
[docs/images/operands.png](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-matrix/docs/images/operands.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201907152138099165-1140%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BCmsXppGdGvZx4VQYR%2BNn8a9pCsEue0oITpjWJW4XJc%3D&st=2019-07-15T21%3A34%3A05Z&se=2019-08-15T21%3A39%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mscharlock** [comment]
David did a review pass via email on this so I am going to squash/merge

**Pull request merged**
