### PR TITLE
[excel] (ExcelAPI 1.9) Removing preview tags for Excel 1.9

### PR DESCRIPTION
**Pull request by AlexJerabek**
This removes any preview tags from API descriptions going out with the 1.9 release.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[36cd502](https://github.com/OfficeDev/office-js-docs-pr/pull/946/commits/36cd502c566984b337a8d7f2e7dc33001598930e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-events.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-shapes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-shapes.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-tables.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/performance.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C30%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904302053473632-946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=V6dI9r6Ci93VNnKh9NHGDB%2Fky%2F2DtMpwO%2BHfjEAIBMc%3D&st=2019-04-30T20%3A49%3A56Z&se=2019-05-31T20%3A54%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
@kbrandl Just got word from the API team and couple of these items didn't actually make it out of preview for this release. I'm going to close the PR and sort everything out.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[36cd502](https://github.com/OfficeDev/office-js-docs-pr/pull/946/commits/36cd502c566984b337a8d7f2e7dc33001598930e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-events.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-shapes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-shapes.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-tables.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/performance.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905011916517455-946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SZDVA84co4XALjZyxPd3eCCpcpB00Z1QC5i5A182BRU%3D&st=2019-05-01T19%3A13%3A02Z&se=2019-06-01T19%3A18%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[86b0ae9](https://github.com/OfficeDev/office-js-docs-pr/pull/946/commits/86b0ae91ad47001cbb006bf39fafc9604d4a3ede)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-events.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-events.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-multiple-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-multiple-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-pivottables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-pivottables.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges-advanced.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges-advanced.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-ranges.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-ranges.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-shapes.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-shapes.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-tables.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-tables.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-workbooks.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-worksheets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/excel-add-ins-worksheets.md) | :white_check_mark:Succeeded | |
[docs/excel/performance.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/excel/performance.md) | :white_check_mark:Succeeded | |
[docs/reference/requirement-sets/excel-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ExcelRelease/docs/reference/requirement-sets/excel-api-requirement-sets.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201905011917020239-946%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uyL%2BgYWnkcD9AkplMMuk7bdOT0r1mrM3XLE8VByxR1E%3D&st=2019-05-01T19%3A14%3A26Z&se=2019-06-01T19%3A19%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
