### PR TITLE
Improve Windows sideloading article

### PR DESCRIPTION
**Pull request by kbrandl**
Addresses issue #333.

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/sideload-windows-network-access-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-network-access-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog-2.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-trust-center-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-trust-center-dialog.png) | :white_check_mark:Succeeded | |
[docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810172058162341-482%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fEsymep%2FL%2F3ocXIiMMm2Qnro94tSK6HpJp9xx6He42M%3D&st=2018-10-17T20%3A54%3A32Z&se=2018-11-17T20%3A59%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/sideload-windows-network-access-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-network-access-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog-2.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-trust-center-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-trust-center-dialog.png) | :white_check_mark:Succeeded | |
[docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810172100461116-482%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZzYS%2FlazwCFAXgiskDPT9ubOT%2BEQLgnEhyNp1jxeaQs%3D&st=2018-10-17T20%3A57%3A08Z&se=2018-11-17T21%3A02%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/sideload-windows-network-access-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-network-access-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog-2.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog-2.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-properties-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-properties-dialog.png) | :white_check_mark:Succeeded | |
[docs/images/sideload-windows-trust-center-dialog.png](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/images/sideload-windows-trust-center-dialog.png) | :white_check_mark:Succeeded | |
[docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-update-sideloading/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810172137413900-482%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EAaLVO6wdsOXOWZHbQD39absYecFRi3CXmw94o%2B04no%3D&st=2018-10-17T21%3A34%3A00Z&se=2018-11-17T21%3A39%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@Rick-Kirkham good feedback; thank you. I've updated the article per your feedback and will merge this PR now. Thanks again!

**Pull request merged**
