### PR TITLE
Merge to live!

### PR DESCRIPTION
**Pull request by lindalu-MSFT**
* Range.moveTo section
* Fix link
* Correcting headers
* Correcting headers

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[af58175](https://github.com/OfficeDev/office-js-docs-pr/commits/af58175b445844b2abb637e9f3377ce929966e83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-96f41f87)

<a id="96f41f87"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in https://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C12%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202002121730179944-1591%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9bQgtnUrnvXipqATZHTBLy%2FEP%2BvmMQri6QLLOlnlI9I%3D&st=2020-02-12T17%3A30%3A04Z&se=2020-03-14T17%3A35%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@AlexJerabek I accidentally merged this to live even though there was a validation error. Can you please revert this, fix whatever is wrong (it could just need to be remerged to master) and let me know? Thanks!

**Comment by AlexJerabek** [comment]
@lindalu-MSFT The [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C12%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202002121730179944-1591%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9bQgtnUrnvXipqATZHTBLy%2FEP%2BvmMQri6QLLOlnlI9I%3D&st=2020-02-12T17%3A30%3A04Z&se=2020-03-14T17%3A35%3A04Z&sp=r) says it's a backend error. I'll kick off another build of the master branch to confirm.

**Comment by lindalu-MSFT** [comment]
@AlexJerabek OK I'll keep my eye on it! Thanks for responding so quickly.

**Pull request merged**
