### PR TITLE
[admin] (Resources) Updating feature request guidance

### PR DESCRIPTION
**Pull request by AlexJerabek**
Updating the feature request links to point to Tech Community. @lindalu-MSFT, is this accurate guidance for our customers in the post-UserVoice world?

### CODE REVIEW

**Review by lindalu-MSFT — APPROVED** [review]
looks good to me!

**Comment by AlexJerabek** [comment]
@lindalu-MSFT Thanks! I'll make some changes in corresponding repos. Should Office Scripts point here too?

**Comment by lindalu-MSFT** [comment]
@AlexJerabek Yes, do you think we need a separate label for office-scripts? Or is the "office-add-ins-development" label good for now?

**Comment by AlexJerabek** [comment]
@lindalu-MSFT I think a separate label makes sense. The two platforms are for different audiences and have different API surfaces. Is "office-scripts" a good enough label? That way, we can capture feature requests that are not only about script development, but end-user facing features like the Recorder and script sharing.

**Pull request merged**
