### PR TITLE
[DO NOT MERGE | DO NOT REVIEW] Custom functions tutorial

### PR DESCRIPTION
**Pull request by mscharlock**
Please note that some of the instructions in the beginning section discussing yo office are subject to change - it seems that they are making changes today based on a bug bash this afternoon.

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-table.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/tutorials/excel-tutorial-create-table.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809191843203446-381%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=42iKK7E9GhaV4EU%2Bbwr8JxAV%2F045ocRYqkciYHQJLcs%3D&st=2018-09-19T18%3A39%3A50Z&se=2018-10-20T18%3A44%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock this PR contains changes to 7 files (including the ones that are part of PR #380) -- should it?  Based on the PR title, I'd expect that it should only contain changes to files that are related to the Custom Functions tutorial. Suggest that you resolve this issue with the PR, so that folks are clear about what you need feedback on (and don't waste their time providing feedback on things that are already part of another PR).

**Comment by mscharlock** [comment]
Sorry about that - this PR didn't start from master so it's got a bunch of other stuff in it. I'll resubmit the PR with a clean copy. Thanks.

**Comment by kbrandl** [comment]
Closing this PR again, since re-opening it didn't make Ricky's prior comments visible.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |
[docs/images/yo-office-excel-cfs-stock-ticker.PNG](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/images/yo-office-excel-cfs-stock-ticker.PNG) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |
[docs/tutorials/excel-tutorial-create-table.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-customfunctut/docs/tutorials/excel-tutorial-create-table.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809192020264588-381%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CezJMArEk2AdT3NvlXkZdT7J2FEFNBA%2B9mOVN4o8HzQ%3D&st=2018-09-19T20%3A16%3A50Z&se=2018-10-20T20%3A21%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
