### PR TITLE
[Outlook] (manifest) update key and property name

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
Fixes [4806](https://github.com/OfficeDev/office-js-docs-pr/issues/4806)

### CODE REVIEW

**Comment by samantharamon** [comment]
Thanks for catching this. We'll also need to update the following articles that mention "MobileButton" and "buttonType".

- [Log appointment notes to an external application in Outlook mobile add-ins](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-log-appointments) - mentions "MobileButton" and "buttonType"
- [Create an Outlook add-in for an online-meeting provider](https://learn.microsoft.com/office/dev/add-ins/outlook/online-meeting) - mentions "MobileButton" and "buttonType"
- [Add-ins for Outlook on mobile devices](https://learn.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins) - mentions "MobileButton" and "buttonType"
- [Create custom contextual tabs in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/contextual-tabs) - mentions "MobileButton"
- [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/office/dev/add-ins/develop/unified-manifest-overview) - mentions "MobileButton"

**Comment by Rick-Kirkham** [comment]
> Thanks for catching this. We'll also need to update the following articles that mention "MobileButton" and "buttonType".
> 
> * [Log appointment notes to an external application in Outlook mobile add-ins](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-log-appointments) - mentions "MobileButton" and "buttonType"
> * [Create an Outlook add-in for an online-meeting provider](https://learn.microsoft.com/office/dev/add-ins/outlook/online-meeting) - mentions "MobileButton" and "buttonType"
> * [Add-ins for Outlook on mobile devices](https://learn.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins) - mentions "MobileButton" and "buttonType"
> * [Create custom contextual tabs in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/contextual-tabs) - mentions "MobileButton"
> * [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/office/dev/add-ins/develop/unified-manifest-overview) - mentions "MobileButton"

Good catch. I'll add these to the PR.

**Comment by Rick-Kirkham** [comment]
> > Thanks for catching this. We'll also need to update the following articles that mention "MobileButton" and "buttonType".
> > 
> > * [Log appointment notes to an external application in Outlook mobile add-ins](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-log-appointments) - mentions "MobileButton" and "buttonType"
> > * [Create an Outlook add-in for an online-meeting provider](https://learn.microsoft.com/office/dev/add-ins/outlook/online-meeting) - mentions "MobileButton" and "buttonType"
> > * [Add-ins for Outlook on mobile devices](https://learn.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins) - mentions "MobileButton" and "buttonType"
> > * [Create custom contextual tabs in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/contextual-tabs) - mentions "MobileButton"
> > * [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/office/dev/add-ins/develop/unified-manifest-overview) - mentions "MobileButton"
> 
> Good catch. I'll add these to the PR.

@samantharamon The contextual tabs article should not be changed. The JSON you see there is in a special JSON extension of the XML manifest. It has a different schema from the unified manifest and that schema hasn't changed.

**Review by samantharamon — APPROVED** [review]

**Comment by samantharamon** [comment]
> > > Thanks for catching this. We'll also need to update the following articles that mention "MobileButton" and "buttonType".
> > > 
> > > * [Log appointment notes to an external application in Outlook mobile add-ins](https://learn.microsoft.com/office/dev/add-ins/outlook/mobile-log-appointments) - mentions "MobileButton" and "buttonType"
> > > * [Create an Outlook add-in for an online-meeting provider](https://learn.microsoft.com/office/dev/add-ins/outlook/online-meeting) - mentions "MobileButton" and "buttonType"
> > > * [Add-ins for Outlook on mobile devices](https://learn.microsoft.com/office/dev/add-ins/outlook/outlook-mobile-addins) - mentions "MobileButton" and "buttonType"
> > > * [Create custom contextual tabs in Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/contextual-tabs) - mentions "MobileButton"
> > > * [Office Add-ins with the unified app manifest for Microsoft 365](https://learn.microsoft.com/office/dev/add-ins/develop/unified-manifest-overview) - mentions "MobileButton"
> > 
> > 
> > Good catch. I'll add these to the PR.
> 
> @samantharamon The contextual tabs article should not be changed. The JSON you see there is in a special JSON extension of the XML manifest. It has a different schema from the unified manifest and that schema hasn't changed.

Ah, that's right!

Changes look good.

**Pull request merged**
