### PR TITLE
[Excel] (PivotTable) Adding A PivotTable object model UML diagram

### PR DESCRIPTION
**Pull request by AlexJerabek**
This PR adds a diagram that highlights the key relationships of the PivotTable object model. It should provide a visual companion for the reference docs and the rest of the conceptual article.

### CODE REVIEW

**Review by alison-mk — COMMENTED** [review]
I have a stylistic concern about the diagram. The kerning between the letters is inconsistent, which makes it hard to read. Is there anything we can do about this?

**Comment by AlexJerabek** [comment]
@alison-mk Let me try a couple things to address that. It looks like a export artifact, rather than a rendering one.

**Comment by AlexJerabek** [comment]
@alison-mk Here's the link to the latest rendering: https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables?branch=AlexJ-PivotPicture

I increased the export resolution, aligned the Visio diagram to page boundaries, and reduced the width. I'm not seeing the same kerning issues. Are you?

**Review by alison-mk — APPROVED** [review]
The new version is much easier to read. Thanks!

**Pull request merged**
