### PR TITLE
Image Updates

### PR DESCRIPTION
**Pull request by bitclash**
Added updated illustrations for _office-add-ins.md_ documentation for review by @Reezaali.

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/ux-design-pattern-templates.md](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/design/ux-design-pattern-templates.md) | :warning:Warning | | [Details](#user-content-docs%2Fdesign%2Fux-design-pattern-templates.md)
[.DS_Store](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/.DS_Store) | :white_check_mark:Succeeded | |
[docs/.DS_Store](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/.DS_Store) | :white_check_mark:Succeeded | |
[docs/images/.DS_Store](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/.DS_Store) | :white_check_mark:Succeeded | |
[docs/images/AddInCommands.png](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/AddInCommands.png) | :white_check_mark:Succeeded | |
[docs/images/ComponentsHelloWorldOffice.png](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/ComponentsHelloWorldOffice.png) | :white_check_mark:Succeeded | |
[docs/images/ContentAddIn.png](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/ContentAddIn.png) | :white_check_mark:Succeeded | |
[docs/images/ManifestWebpage.png](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/ManifestWebpage.png) | :white_check_mark:Succeeded | |
[docs/images/TaskPane.png](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/images/TaskPane.png) | :white_check_mark:Succeeded | |
[docs/overview/.DS_Store](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/overview/.DS_Store) | :white_check_mark:Succeeded | |
[docs/overview/office-add-ins.md](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/overview/office-add-ins.md) | :white_check_mark:Succeeded | |

<a name="docs%2Fdesign%2Fux-design-pattern-templates.md"></a>
### [docs/design/ux-design-pattern-templates.md](https://github.com/bitclash/office-js-docs-pr/blob/imageUpdates/docs/design/ux-design-pattern-templates.md)
 - **Line 25**: **[Warning]** Invalid file link:(~/first-run-experience-patterns.md).
 - **Line 26**: **[Warning]** Invalid file link:(~/authentication-patterns.md).
 - **Line 27**: **[Warning]** Invalid file link:(~/navigation-patterns.md).
 - **Line 28**: **[Warning]** Invalid file link:(~/branding-patterns.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201806151907435870-213%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ollmAIIZ65YpXtaG63bB65mYg9wy%2BSQPryBIoqJrsFY%3D&st=2018-06-15T19%3A03%3A46Z&se=2018-07-16T19%3A08%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by hodlhodl** [comment]
@lindalu-MSFT @Lauragra is it possible to publish the updated images for the About Office Add-ins page without processing the ux-design-pattern-templates.md? We'd like to see these go live.

**Comment by lindalu-MSFT** [comment]
@hodlhodl The only way to do that is to merge the images separately. You would need to take the individual image files and merge them to the https://github.com/OfficeDev/office-js-docs-pr/tree/master/docs/images folder. Otherwise, when I merge this, I will be updating the entire file.

**Comment by lindalu-MSFT** [comment]
@hodlhodl Mei Li, I will hold off on the PR until I hear what you want me to do.

**Comment by hodlhodl** [comment]
@lindalu-MSFT let's close this PR and use #219 instead. Thanks!

**Pull request closed without merging**
