### PR TITLE
Update TaskPaneAppVersionOverridesV1_0.xsd

### PR DESCRIPTION
**Pull request by Goldensky321**
A copy from Dev enlistment

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[fcfd96c](https://github.com/Goldensky321/office-js-docs-pr/pull/1104/commits/fcfd96c97d0d9fbc1b4a4ef825f1f087becface3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd](https://github.com/Goldensky321/office-js-docs-pr/blob/patch-2/docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201906181843527914-1104%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8f8sqS0co4jfgVPGC5B1sKZzmg4fvMEB8diCQqdUxHs%3D&st=2019-06-18T18%3A39%3A49Z&se=2019-07-19T18%3A44%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@Goldensky321 thanks for the contribution. FYI, I'll need to do an edit pass on the new content before this PR gets merged (and will push any edits to the source branch in your fork); in the meantime, I've added the label `hold: in-progress` to this PR so that no one else will inadvertently merge it. Thanks!

**Comment by o365devx** [comment]
Docs Build status updates of commit _[44b6a98](https://github.com/Goldensky321/office-js-docs-pr/pull/1104/commits/44b6a98bbc9a87b747bf7760530e2cb935d1d604)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd](https://github.com/Goldensky321/office-js-docs-pr/blob/patch-2/docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201906202027228028-1104%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4WlCdMq9EDeXaJxhJBNmaOG%2BmoOBANaSOzP7ASSlh2Q%3D&st=2019-06-20T20%3A23%3A24Z&se=2019-07-21T20%3A28%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[c61ff3f](https://github.com/Goldensky321/office-js-docs-pr/pull/1104/commits/c61ff3fd4f25ef49a792a50290316b3fffd9945f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd](https://github.com/Goldensky321/office-js-docs-pr/blob/patch-2/docs/overview/schemas/taskpane/TaskPaneAppVersionOverridesV1_0.xsd) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201906202029213994-1104%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NHZRMDoSGoeNoJcubHBLjzXDmJMkL6oMOCmovh1UjcQ%3D&st=2019-06-20T20%3A25%3A20Z&se=2019-07-21T20%3A30%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
I've applied a handful of minor editorial changes to some documentation element values in the xsd file. I'll merge this PR now.

**Pull request merged**
