### PR TITLE
[All hosts] (admin) Refactor file structure for all quick starts.

### PR DESCRIPTION
**Pull request by kbrandl**
Note: this PR doesn't change any of the content that the user sees in the quick starts; it merely changes which underlying files make up each quick start. It eliminates the use of an "include" file for each quick start, which will improve SEO and simplify content maintenance.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[10bb064](https://github.com/OfficeDev/office-js-docs-pr/pull/731/commits/10bb0648801260af98c8eed37176c984a8eb4fef)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[10bb064](https://github.com/OfficeDev/office-js-docs-pr/pull/731/commits/10bb0648801260af98c8eed37176c984a8eb4fef)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[10bb064](https://github.com/OfficeDev/office-js-docs-pr/pull/731/commits/10bb0648801260af98c8eed37176c984a8eb4fef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[docs/develop/create-and-debug-office-add-ins-in-visual-studio.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/develop/create-and-debug-office-add-ins-in-visual-studio.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/excel/excel-add-ins-get-started-angular.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/excel/excel-add-ins-get-started-jquery.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/excel/excel-add-ins-get-started-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/excel/excel-add-ins-get-started-react.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-get-started-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/excel/excel-add-ins-get-started-vue.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-excel-angular.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-excel-jquery.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-excel-react.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-excel-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-excel-vue.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-onenote.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-onenote.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-powerpoint.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-powerpoint.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-project.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-project.md) | :white_check_mark:Succeeded | |
[docs/includes/file-get-started-word.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/includes/file-get-started-word.md) | :white_check_mark:Succeeded | |
[docs/onenote/onenote-add-ins-getting-started.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/onenote/onenote-add-ins-getting-started.md) | :white_check_mark:Succeeded | |
[docs/onenote/onenote-add-ins-programming-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/onenote/onenote-add-ins-programming-overview.md) | :white_check_mark:Succeeded | |
[docs/powerpoint/powerpoint-add-ins-get-started.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/powerpoint/powerpoint-add-ins-get-started.md) | :white_check_mark:Succeeded | |
[docs/project/project-add-ins-get-started.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/project/project-add-ins-get-started.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-angular.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/excel-quickstart-angular.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-jquery.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/excel-quickstart-jquery.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-react.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/excel-quickstart-react.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/excel-quickstart-vue.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/excel-quickstart-vue.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/onenote-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/onenote-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/powerpoint-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/powerpoint-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/project-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/project-quickstart.md) | :white_check_mark:Succeeded | |
[docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/quickstarts/word-quickstart.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/toc.yml) | :white_check_mark:Succeeded | |
[docs/word/word-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/kb-refactor-remove-include-files/docs/word/word-add-ins.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902012146281312-731%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=z5FRmlZ8hBLnIolA5dFqQ0UKjXiHQ%2Bwqk%2FK0HpZwYQE%3D&st=2019-02-01T21%3A42%3A47Z&se=2019-03-04T21%3A47%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@AlexJerabek a polite nudge on this one. It shouldn't be very time consuming to review -- even though 29 files were changed, the updates involved just copying/pasting blocks of content from one place to another, deleting now unnecessary files, adding redirects for the deleted files, and updating TOC links. 

Instead of reviewing the file diffs in detail here within this PR, you could simply verify that each quick start on the staging site loads correctly and contains the correct content. If you take this approach, test each quick start link under **Quick Starts** in the TOC and the corresponding link under **How-to guides** > **[product] add-ins** (each pair of related links in these two TOC locations should point to the same URL now).

**Pull request merged**
