### PR TITLE
[Excel](Custom Functions) Updates to tutorial for associate change

### PR DESCRIPTION
**Pull request by mscharlock**

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[45a3193](https://github.com/OfficeDev/office-js-docs-pr/pull/664/commits/45a319324ab775ea6b2b7ed0867199e6e75b63c3)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[45a3193](https://github.com/OfficeDev/office-js-docs-pr/pull/664/commits/45a319324ab775ea6b2b7ed0867199e6e75b63c3)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[45a3193](https://github.com/OfficeDev/office-js-docs-pr/pull/664/commits/45a319324ab775ea6b2b7ed0867199e6e75b63c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/tutorials/excel-tutorial-create-custom-functions.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-associateupdatetut/docs/tutorials/excel-tutorial-create-custom-functions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C4%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201901042158455040-664%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Whj3BKCtIVCzjmTeJ6GP2k4PrSs7nLBtIu0ksscFOTs%3D&st=2019-01-04T21%3A54%3A59Z&se=2019-02-04T21%3A59%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
I pulled these changes into a new PR https://github.com/OfficeDev/office-js-docs-pr/pull/666 

So I will close this one since it is superseded.

**Pull request closed without merging**
