### PR TITLE
[Excel] (Custom Functions) Added link to local loopback exception article

### PR DESCRIPTION
**Pull request by mscharlock**
Added the "local loopback exception" info to our troubleshooting article. I'm not sure if there are other instances in which this happens - it might be worth talking to Juan quickly on this because I know he didn't hit a specific error.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[17bf508](https://github.com/OfficeDev/office-js-docs-pr/pull/858/commits/17bf508e81a19f208833f3c7ace2ea93b2badb54)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-loopback/docs/excel/custom-functions-troubleshooting.md) | :bulb:Suggestion | | [Details](#user-content-docs%2Fexcel%2Fcustom-functions-troubleshooting.md)

<a name="docs%2Fexcel%2Fcustom-functions-troubleshooting.md"></a>
### [docs/excel/custom-functions-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-loopback/docs/excel/custom-functions-troubleshooting.md)
 - **Line 11**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#verify-ssl-certificates&quot;&gt;verifying ssl certificates&lt;/a&gt;` -- missing bookmark. The file excel/custom-functions-troubleshooting.md doesn&#39;t contain a bookmark named verify-ssl-certificates.
 - **Line 11**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#associate-your-functions&quot;&gt;associate your functions&lt;/a&gt;` -- missing bookmark. The file excel/custom-functions-troubleshooting.md doesn&#39;t contain a bookmark named associate-your-functions.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C30%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201903300012594260-858%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1ayhXESdlLweev%2FOHRLXth8pP77%2F6%2BitUWEIBDCu0hk%3D&st=2019-03-30T00%3A09%3A15Z&se=2019-04-30T00%3A14%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
Also don't forget to update the date in the article.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[2a67c51](https://github.com/OfficeDev/office-js-docs-pr/pull/858/commits/2a67c514b9d034036de391f45c50c601f3ba82d5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7e472974)

<a id="7e472974"></a>
###
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\0tym-s, target branch: master, target branch commit: cadac8c0d396bb6fd400886fea5a747ccc3c6de3, source branch: michelle-loopback, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904181746154488-858%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=La3YJKgqN272P65r%2BT7oysOWt%2BcYPIYoll5GFd2jMNU%3D&st=2019-04-18T17%3A41%3A27Z&se=2019-05-19T17%3A46%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[a83b084](https://github.com/OfficeDev/office-js-docs-pr/pull/858/commits/a83b08409246a9182f151f7ff852c176e52c17cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-loopback/docs/excel/custom-functions-troubleshooting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201904181841171189-858%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=f8%2BdS51qlfPU00NKU7RqAe2At4Cspe8CNi2xIUG6z%2BA%3D&st=2019-04-18T18%3A37%3A27Z&se=2019-05-19T18%3A42%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
