### PR TITLE
Updates per MZ's feedback

### PR DESCRIPTION
**Pull request by mscharlock**
@kbrandl I feel like there might be too many notes going on in this one, but let's chat on Monday.

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809290135544088-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fPptR5fbyLnHPGigMHtrgZH06x9zSHJuEDHfb8BWWgg%3D&st=2018-09-29T01%3A32%3A08Z&se=2018-10-30T01%3A37%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fexcel%2Fcustom-functions-overview.md)
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

<a name="docs%2Fexcel%2Fcustom-functions-overview.md"></a>
### [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md)
 - **Line 194**: **[Warning]** Illegal link: `[XHR](custom-functions-runtime.md#xhr)` -- missing bookmark. The file excel/custom-functions-runtime.md doesn&#39;t contain a bookmark named xhr.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810012345106218-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1I3XoKdR197eydyYSStch0opvz%2FLBTC5dBIhNBFVgcc%3D&st=2018-10-01T23%3A41%3A27Z&se=2018-11-01T23%3A46%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fexcel%2Fcustom-functions-overview.md)
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

<a name="docs%2Fexcel%2Fcustom-functions-overview.md"></a>
### [docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md)
 - **Line 194**: **[Warning]** Illegal link: `[XHR](custom-functions-runtime.md#xhr)` -- missing bookmark. The file excel/custom-functions-runtime.md doesn&#39;t contain a bookmark named xhr.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810012347581765-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qTRtfyKwqsgA8ZbkKLhU4Hkln5w0T2wYr2J4%2FruBw9k%3D&st=2018-10-01T23%3A44%3A15Z&se=2018-11-01T23%3A49%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810012350205952-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZiT3G08WunK3FcX%2Blv7vJ2zGqbb2p7wDdA8Aj5RN%2FJA%3D&st=2018-10-01T23%3A46%3A42Z&se=2018-11-01T23%3A51%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mscharlock** [comment]
I want to have one more look through this tomorrow - hold on a merge

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C1%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810012354320248-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zUcET%2BgTtuP4yZjodcsxqx068iMePv0uzZzexQ7S5Uc%3D&st=2018-10-01T23%3A50%3A45Z&se=2018-11-01T23%3A55%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-mzfixes/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810021935561688-428%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=y6T5r4ShFAyXEcWrBrE79ZaU4AbX%2F3AdzSCSdpdeB2k%3D&st=2018-10-02T19%3A32%3A05Z&se=2018-11-02T19%3A37%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock I've merged in my changes, reviewed the updated content on the staging site, and approved this PR. Whenever you're ready, please "Squash and merge" this PR into **master**. Thanks!

**Pull request merged**
