### PR TITLE
Updates for Partner Center migration

### PR DESCRIPTION
**Pull request by Lauragra**
This PR updates links/text per updated docs for Partner Center. Current ETA for GA is 10/21 but that date might change; please hold until I set the PR to "Ready to merge". Thanks.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[384d9c4](https://github.com/OfficeDev/office-js-docs-pr/commits/384d9c4a9784239d2d2336e07f2e70d353bc03b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | |
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | |
[docs/develop/usability-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/develop/usability-testing.md) | :white_check_mark:Succeeded | |
[docs/excel/excel-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/excel/excel-add-ins-overview.md) | :white_check_mark:Succeeded | |
[docs/publish/host-an-office-add-in-on-microsoft-azure.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/publish/host-an-office-add-in-on-microsoft-azure.md) | :white_check_mark:Succeeded | |
[docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/lauragra-PartnerCenterMigration/docs/publish/publish.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C16%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201910162332178854-1373%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cGjVI%2FqyEefeMPkVnLYqkLfTcRoq4yw4b47rXknSGnU%3D&st=2019-10-16T23%3A28%3A28Z&se=2019-11-16T23%3A33%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@Lauragra I've added the label **Status: Do Not Merge** to this PR (per your comments above), so that it won't be merged until you give the go ahead. When you're ready to have this PR merged, please add a comment here to request that it be merged. Thanks!

**Comment by Lauragra** [comment]
@kbrandl , FYI, GA is on 12/4 so we'll want to merge this PR tomorrow. I'll remove the do not merge label after I publish the Partner Center docs. Thanks!

**Comment by kbrandl** [comment]
@Lauragra thanks for the update! If you can please @-mention me in another comment here tomorrow whenever you're ready for this PR to be merged, I'll merge it then and subsequently publish the doc updates to **live**. (I won't get an email notification when you remove the label, but if you @-mention me in a comment, I'll get one :)). Thanks!

**Comment by Lauragra** [comment]
@kbrandl , this PR is ready to merge. Thanks!

**Pull request merged**
