### PR TITLE
[All] (troubleshooting) added mac runtime logging info

### PR DESCRIPTION
**Pull request by davidchesnut**

### CODE REVIEW

**Comment by lindalu-MSFT** [comment]
@davidchesnut Are you ready to merge this to master?

**Comment by kbrandl** [comment]
@davidchesnut I notice you've merged this PR without incorporating any of the feedback. Was that intentional?

**Comment by kbrandl** [comment]
@davidchesnut FYI, I'm going to submit another PR to fix the issues I noted during review of this PR -- to prevent this article from being published as-is (with a malformed Note and issues that will cause problems with localization, etc.).

**Comment by kbrandl** [comment]
PR submitted and merged, to fix issues with this article before publication: https://github.com/OfficeDev/office-js-docs-pr/pull/1309.

**Pull request merged**
