### PR TITLE
Code updates to NodeJS SSO walkthrough

### PR DESCRIPTION
**Pull request by davidchesnut**
I updated the dependencies in the SSO sample on GitHub, and needed to make a few code changes as a result. I added these changes to the walkthrough.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4aa52ed](https://github.com/OfficeDev/office-js-docs-pr/pull/631/commits/4aa52ed8bf17f7bcfc71ea38ddaa38b29aaa87a1)_: 

:clock10: **Preparing**: average preparing time is _45 sec(s)_

**Comment by davidchesnut** [comment]
To be clearer, turned out only 1 line of code changed in the walkthrough.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4aa52ed](https://github.com/OfficeDev/office-js-docs-pr/pull/631/commits/4aa52ed8bf17f7bcfc71ea38ddaa38b29aaa87a1)_: 

:clock10: **Incremental building**: average incremental building time is _28 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4aa52ed](https://github.com/OfficeDev/office-js-docs-pr/pull/631/commits/4aa52ed8bf17f7bcfc71ea38ddaa38b29aaa87a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/create-sso-office-add-ins-nodejs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/davech-sso-walkthrough/docs/develop/create-sso-office-add-ins-nodejs.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201812200200292144-631%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XumCsIdNdX5jWlZ3dZTjYlbytgD83Lx9dekIRpMA6Vw%3D&st=2018-12-20T01%3A56%3A42Z&se=2019-01-20T02%3A01%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
