### PR TITLE
Add section for Angular’s AOT compiler

### PR DESCRIPTION
**Pull request by ThorstenHans**
Added a short section that describes the benefits of using Angular's AOT compiler

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/add-ins-with-angular2.md](https://github.com/ThorstenHans/office-js-docs-pr/blob/ng-aot/docs/develop/add-ins-with-angular2.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C19%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810191140511140-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4goJm4ITCCuAQvuFRG5UWgujgBRCF6NlXY2%2FfdjtMXg%3D&st=2018-10-19T11%3A37%3A10Z&se=2018-11-19T11%3A42%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@ThorstenHans thanks for the contribution! We'll review before end of week and update here with the outcome.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/add-ins-with-angular2.md](https://github.com/ThorstenHans/office-js-docs-pr/blob/ng-aot/docs/develop/add-ins-with-angular2.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201811022309373769-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CmeamDhppZEyIeXEg6cJuU1%2Fl9UovREuTo1Gw8gzuUE%3D&st=2018-11-02T23%3A05%3A55Z&se=2018-12-03T23%3A10%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/add-ins-with-angular2.md](https://github.com/ThorstenHans/office-js-docs-pr/blob/ng-aot/docs/develop/add-ins-with-angular2.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201811022312554309-493%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Lro%2FqmlUqO%2BrjD1YgEC8gJpEEmB2%2B%2BLQv3kq5o38e1c%3D&st=2018-11-02T23%3A09%3A13Z&se=2018-12-03T23%3A14%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@ThorstenHans thanks again for the contribution! I made a few very minor updates in your branch and have merged this PR; the updates will show up in the live docs later today.

**Pull request merged**
