### PR TITLE
[excel] (Custom Functions) Fixing CF req set links

### PR DESCRIPTION
**Pull request by AlexJerabek**
Pointing the requirement set links to the Custom Functions requirement set article. Also clarifying that CFs are only for Excel.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d37426d](https://github.com/OfficeDev/office-js-docs-pr/commits/d37426db2bfab7b749c58791ed808f9a0c0a7e66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-FixLinks/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C23%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202001232024327778-1557%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IZRGVBC7ySNL0GzUp3Lg%2FigTCvL4Goz25bC1S0LEnXU%3D&st=2020-01-23T20%3A21%3A07Z&se=2020-02-23T20%3A26%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mscharlock** [comment]
Adding @ElizabethSamuel-MSFT as she has the best guidance on how to frame "office on web" vs other terms. I think this is an ok change but I want to make sure that we also say "Excel on the web" in other places, as this isn't something I typically use.

**Comment by AlexJerabek** [comment]
Thanks @mscharlock and @ElizabethSamuel-MSFT. I took the suggestion of changing the CF header to be "Excel only".

**Comment by o365devx** [comment]
Docs Build status updates of commit _[7b049c8](https://github.com/OfficeDev/office-js-docs-pr/commits/7b049c825b5e302c94ff5cf737ec6be43bfb2efa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/overview/office-add-in-availability.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-FixLinks/docs/overview/office-add-in-availability.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C24%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202001242205201007-1557%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R9FKUjGskE53McMzqsetgSkl0MDKXe14DqdYGg%2BGiyw%3D&st=2020-01-24T22%3A01%3A49Z&se=2020-02-24T22%3A06%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
