### PR TITLE
Update custom-functions-overview.md

### PR DESCRIPTION
**Pull request by keyur32**
@mscharlock , @davidchesnut  - please see update. Cleaned up a few items that were out of date. and instead pointing to our GitHub repo so folks can see this.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce22754](https://github.com/OfficeDev/office-js-docs-pr/pull/737/commits/ce22754d10b644e5114aa388ef8ab037c9ea96da)_: 

:clock10: **Preparing**: average preparing time is _44 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce22754](https://github.com/OfficeDev/office-js-docs-pr/pull/737/commits/ce22754d10b644e5114aa388ef8ab037c9ea96da)_: 

:clock10: **Incremental building**: average incremental building time is _29 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce22754](https://github.com/OfficeDev/office-js-docs-pr/pull/737/commits/ce22754d10b644e5114aa388ef8ab037c9ea96da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyur32-patch-2/docs/excel/custom-functions-overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201902061633120142-737%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hpaveKQF4ViYIErD1LsGwk%2BBiUkkA%2B4yA%2BMSHn8FJ8w%3D&st=2019-02-06T16%3A29%3A22Z&se=2019-03-09T16%3A34%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mscharlock** [comment]
Sounds like a plan to me! Talked with David and we agree this seems like a good place to gather all current errors.

**Comment by davidchesnut** [comment]
@keyur32 @mscharlock I like this change. Known issues are updated frequently and it's easier to manage track and update quickly  in the repo than as a published page.

**Pull request merged**
