### PR TITLE
[Admin] Fix broken links

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**
@Rick-Kirkham The link being used for extended-manifest.schema.json (https://developer.microsoft.com/en-us/json-schemas/office-js/extended-manifest.schema.json) is invalid. Can you provide the current link? Thanks.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[db0404d](https://github.com/OfficeDev/office-js-docs-pr/commits/db0404d11d5f366384cd439bc276e0c8f6613bee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-fix-links/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2329) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011171649278022-2329%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GYJ7hcngruw71f93Lk3KvXnqwDFJiwu3cWcwPtvyvog%3D&st=2020-11-17T16%3A45%3A06Z&se=2020-12-18T16%3A50%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by mohamedbbh** [comment]
nice

**Comment by o365devx** [comment]
Docs Build status updates of commit _[178b51f](https://github.com/OfficeDev/office-js-docs-pr/commits/178b51ffe8952873aa8dc2e2510d41a2ff12c7f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-fix-links/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2329) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011172355230412-2329%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EOlanyjN%2Bjl4vgwlZRMQxUjsS0tKAJ7COSUDsnIe1CE%3D&st=2020-11-17T23%3A51%3A04Z&se=2020-12-18T23%3A56%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d8e7e4c](https://github.com/OfficeDev/office-js-docs-pr/commits/d8e7e4c124e259a6946a4081db5936a0a837f8fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-fix-links/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2329) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011180002473766-2329%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wMqtk54RRzHO2oS15pgwmSUZ95A0fpNSSj%2BAmUQ%2FTjA%3D&st=2020-11-17T23%3A58%3A29Z&se=2020-12-19T00%3A03%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by Rick-Kirkham — APPROVED** [review]

**Pull request merged**
