### PR TITLE
[Outlook] (add-in commands) Note support from 2013

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by ElizabethSamuel-MSFT** [comment]
Waiting for minimum build #.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[2077bde](https://github.com/OfficeDev/office-js-docs-pr/commits/2077bdec7256afd6e4e08995d7f792c3e2cbdb00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-2013/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C4%5C21%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202004212201427211-1775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XjU6Ucc%2FYT6vnuOpoZ4m69UP7booPvlEPm3tn%2FSy%2FAY%3D&st=2020-04-21T21%3A57%3A55Z&se=2020-05-22T22%3A02%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Faisalalmosi** [comment]
ok

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6d4e0ad](https://github.com/OfficeDev/office-js-docs-pr/commits/6d4e0ad370fa1ebc23b4d7a9376bf81af3a4d927)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-2013/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |
[docs/develop/create-addin-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-2013/docs/develop/create-addin-commands.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C12%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202005121612265333-1775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h5Fcl2nHNuWbHKAt8%2Fl35Da8DsttPlQHvBpskC5y6A0%3D&st=2020-05-12T16%3A09%3A07Z&se=2020-06-12T16%3A14%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[bcd87fe](https://github.com/OfficeDev/office-js-docs-pr/commits/bcd87fe6bfbfaf1b625dae71c308959a32740558)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-2013/docs/design/add-in-commands.md) | :white_check_mark:Succeeded | |
[docs/develop/create-addin-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/elizs-2013/docs/develop/create-addin-commands.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C5%5C12%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202005121617037097-1775%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zOPnAPuZhj1y9przn28vsd8dEED8PfUSBUeoEBrBG2Q%3D&st=2020-05-12T16%3A13%3A36Z&se=2020-06-12T16%3A18%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
