### PR TITLE
Describe how to validate manifest for projects created with yo office

### PR DESCRIPTION
**Pull request by ThorstenHans**
The `generator-office` creates `validate` script that could be used to easily validate manifests

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/troubleshoot-manifest.md](https://github.com/ThorstenHans/office-js-docs-pr/blob/validate-generator-office/docs/testing/troubleshoot-manifest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C19%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201810190644470318-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AhK7vVnKUi15e9gRMaNWz%2FIX1QM%2Bg2plN%2F6aC2%2BZRcs%3D&st=2018-10-19T06%3A41%3A08Z&se=2018-11-19T06%3A46%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@ThorstenHans thanks for the contribution! We'll review before end of week and update here with the outcome.

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/OfficeDev/office-js-docs-pr, working directory: W:\lube-s, target branch: master, target branch commit: a698b4459d48302a8de608615b4f5e6deb7efac9, source branch: d1eab01a6400fbdd4a264c6464e13c9a/validate-generator-office, source branch commit: .
Learn more: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201811022218322795-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=a%2Fd%2FWeSbjQg9uHARgadx4BVxeX%2Fv6nfWRRpJJSlD7OU%3D&st=2018-11-02T22%3A13%3A43Z&se=2018-12-03T22%3A18%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/yo-office-validator.gif](https://github.com/ThorstenHans/office-js-docs-pr/blob/validate-generator-office/docs/images/yo-office-validator.gif) | :white_check_mark:Succeeded | |
[docs/testing/troubleshoot-manifest.md](https://github.com/ThorstenHans/office-js-docs-pr/blob/validate-generator-office/docs/testing/troubleshoot-manifest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C2%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201811022238287995-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tR3%2B5l%2Bg2Gz6zMEH90KziR0%2BXJRjXS%2FOA8RxK2rz6jA%3D&st=2018-11-02T22%3A34%3A43Z&se=2018-12-03T22%3A39%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@ThorstenHans thanks again for the contribution! I made a few very minor updates in your branch and have merged this PR; the updates will show up in the live docs later today. Thanks again!

**Pull request merged**
