### PR TITLE
Adding beta events

### PR DESCRIPTION
**Pull request by AlexJerabek**
Added the beta events based on what's in the [open spec](https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/new-events.md).

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Not sure why I can't tag @ShawnNiu as a reviewer, but I believe this is his feature area :-)

**Comment by ShawnNiu** [comment]
Yes, please add me to api related issues. Thanks Alex :)

**Comment by AlexJerabek** [comment]
@ShawnNiu GitHub won't let officially add you as a reviewer, but please give me any feedback on this PR you have. I'll check in if you approve in the comments.

**Comment by AlexJerabek** [comment]
Hey @lindalu-MSFT, why did this get merged? I was still waiting on someone from the feature crew to review the content. Is there additional tagging I should use?

**Pull request merged**
