### PR TITLE
Update powerpoint-tutorial.md

### PR DESCRIPTION
**Pull request by tanure**
I was tried to execute this tutorial to reproduce this example, but I'd many problems when executed the application. The solution's to configure correctly the scripts and CSS of the page and then the correct javascript class to create messageBanner.

With these changes I was able to reproduce the tutorial successfully.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f748b03](https://github.com/tanure/office-js-docs-pr/commits/f748b03adb325072edcc776c7a610311ce04b397)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/tutorials/powerpoint-tutorial.md](https://github.com/tanure/office-js-docs-pr/blob/master/docs/tutorials/powerpoint-tutorial.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C25%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201910251409426588-1391%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rKn%2F3UuokH4qCfn5kwLxAoeZs7BXKhpUugr%2BflOc1ns%3D&st=2019-10-25T14%3A05%3A58Z&se=2019-11-25T14%3A10%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@tanure thanks for the contribution! I'll review this PR later today.

**Comment by kbrandl** [comment]
@tanure I'm having trouble getting the revised tutorial to work. Can you tell me what version of Visual Studio you're using to create your project? Thanks!

**Comment by tanure** [comment]
I was use the Vishal Studio 2019.

**Comment by kbrandl** [comment]
@tanure thanks again for submitting this PR to share with others how you got things working in Visual Studio 2019. After further investigation on my part, it turns out that the old instructions (valid for Visual Studio 2017) did not work properly in projects created with Visual Studio 2019 -- because Office Add-ins projects created with Visual Studio 2019 no longer use Fabric _components_.

I've submitted PR #1397 to update the PowerPoint tutorial such that the instructions work when you create the Office Add-in project using Visual Studio 2019, and the live docs will be updated soon (once that PR gets merged). In the meantime, you can see the updated article here via the PR itself: https://github.com/OfficeDev/office-js-docs-pr/blob/ece568eb23fc5f05c151ac56edd6bca86d0bed62/docs/tutorials/powerpoint-tutorial.md. As you'll see, the changes in my PR don't update the `<head>` section of HTML, so it's a bit cleaner in terms of implementation. 

I'm going to go ahead and close this PR now (without merging); please feel free to try to the updated tutorial instructions I've linked to above, and let me know if you have any feedback. Thanks!

**Pull request closed without merging**
