### PR TITLE
Updates to best practices to give guidance

### PR DESCRIPTION
**Pull request by mscharlock**
Since CFMapping is now required, Kim & I plan to move that content to the overview. Thus, the best practices should reflect actual guidance and not a definition of what it is.

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-bps/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809271701508966-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=71IEqKJg3DxCPtK1dz0v9tqa%2FHkxdCiJUvLJEAejF88%3D&st=2018-09-27T16%3A58%3A04Z&se=2018-10-28T17%3A03%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock -- please don't merge this PR (or any other custom functions PR that you submit) until I approve the PR. While the other Reviewers may provide good feedback about things like wording, formatting, etc., they don't have enough knowledge about Custom Functions to be able to provide constructive feedback about the content itself.  Thx

**Comment by mscharlock** [comment]
Ok sounds like a plan!

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/michelle-bps/docs/excel/custom-functions-best-practices.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C27%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C201809271946031504-420%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FYvjL%2FVTPVeNq2ZFmAjdb%2Bh90%2FxPNGAtoyUaRhfNAuk%3D&st=2018-09-27T19%3A42%3A17Z&se=2018-10-28T19%3A47%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@mscharlock I've approved this PR so please feel free to merge it to **master**.

**Pull request merged**
